import { Config } from '../core/Config.js';
import { CharacterMovement } from '../entities/CharacterMovement.js';
import { House } from '../entities/House.js';
import { Dwelling } from '../entities/Dwelling.js';
import { Household } from '../households/Household.js';
import { Pathfinder } from '../world/Pathfinder.js';
import { Settlement } from './Settlement.js';
import { SettlementNameGenerator } from './SettlementNameGenerator.js';
import { SettlementRules } from './SettlementRules.js';

export class ExaltedFoundingSystem {
  constructor(world, data = {}) { this.world = world; this.reservations = [...(data.reservations ?? [])]; this.journeys = { ...(data.journeys ?? {}) }; this.movements = new Map(); }
  evaluate() { if (this.world.settlements.length + this.reservations.length >= Config.MAX_SETTLEMENTS) { this.world.diagnostics.trace('thirdSettlementLimitReached'); return null; } const founder = this.world.characters.find(character => SettlementRules.canFoundNewSettlement(character, this.world)); if (!founder) return null; this.world.diagnostics.trace('exaltedFounderEligible', { characterId: founder.id }); return this.begin(founder); }
  begin(founder) { if (!SettlementRules.canFoundNewSettlement(founder, this.world)) return null; const position = this.world.findSettlementFoundingPosition(founder.position); if (!position) return null; const reservation = { id: `founding-${founder.id}`, founderId: founder.id, position, waterSourceId: position.waterSourceId, memberIds: this.familyIds(founder) }; const source=this.world.waterSources.find(item=>item.id===reservation.waterSourceId); if(!source||source.reservedByFoundingId)return null; source.reservedByFoundingId=reservation.id; this.reservations.push(reservation); for (const id of reservation.memberIds) { const member = this.world.characters.find(character => character.id === id); if (member) member.foundingState = 'journey'; } this.journeys[founder.id] = { reservationId: reservation.id, stage: 'traveling' }; this.startMovement(founder, position); this.world.addEffect(founder.position, 'settlementTransform', { duration: 5, settlementName: founder.name, message: `${founder.name} sente che il suo destino non termina qui.` }); this.world.diagnostics.trace('exaltedFounderSelected', { characterId: founder.id }); this.world.diagnostics.trace('foundingSlotReserved', { characterId: founder.id }); this.world.diagnostics.trace('foundingJourneyStarted', { characterId: founder.id, position }); return reservation; }
  familyIds(founder) { const ids = [founder.id]; const partner = this.world.characters.find(character => character.id === founder.partnerId && character.alive); if (partner) { ids.push(partner.id); for (const child of this.world.characters.filter(character => character.alive && character.lifeStage === 'child' && character.parentIds.includes(founder.id))) ids.push(child.id); } return [...new Set(ids)]; }
  startMovement(founder, target) { const movement = new CharacterMovement(founder); movement.follow(new Pathfinder().findPath(this.world.terrain, founder.position, target)); this.movements.set(founder.id, movement); founder.visualState = 'walk'; }
  update(deltaTime) { for (const reservation of [...this.reservations]) { const founder = this.world.characters.find(character => character.id === reservation.founderId && character.alive); if (!founder) { this.cancel(reservation); continue; } let movement = this.movements.get(founder.id); if (!movement) { this.startMovement(founder, reservation.position); movement = this.movements.get(founder.id); } if (movement.update(deltaTime)) this.complete(reservation, founder); else this.moveFamilyWith(founder, reservation.memberIds); } }
  moveFamilyWith(founder, ids) { for (const id of ids.filter(item => item !== founder.id)) { const member = this.world.characters.find(character => character.id === id && character.alive); if (member) member.position = { x: founder.position.x + .5, y: founder.position.y + .5 }; } }
  complete(reservation, founder) { if (this.world.settlements.length >= Config.MAX_SETTLEMENTS) return this.cancel(reservation); const number = this.world.settlements.length + 1; const settlementId = `settlement-${number}`; const home = new House({ id: `home-${this.world.nextEntityId++}`, position: reservation.position, completed: true, visualVariant: Dwelling.variant(this.world.worldType, true, founder.species), settlementId, occupancy: 'occupied' }); const household = new Household({ id: `household-${this.world.households.length + 1}`, memberIds: reservation.memberIds, homeBuildingId: home.id, settlementId }); const settlement = new Settlement({ id: settlementId, name: new SettlementNameGenerator().generate(this.world.worldSeed + number * 97), founderId: founder.id, householdIds: [household.id], homeBuildingIds: [home.id], foundingHomeId: home.id, center: home.position, state: Settlement.States.GROWING, externalArrivalCount: 0, waterSourceId: reservation.waterSourceId }); home.householdId = household.id; this.world.homes.push(home); this.world.households.push(household); for (const id of reservation.memberIds) { const member = this.world.characters.find(character => character.id === id); if (!member) continue; const previous = this.world.households.find(item => item.id === member.householdId); previous?.removeMember(id); member.householdId = household.id; member.homeBuildingId = home.id; member.settlementId = settlement.id; member.homeSettlementId = settlement.id; member.foundingState = null; member.position = { ...home.position }; } const source=this.world.waterSources.find(item=>item.id===reservation.waterSourceId); if(!this.world.settlementWater.claim(settlement,source)) return this.cancel(reservation); founder.hasFoundedSettlement=true; founder.canFoundSettlement=false; this.world.settlements.push(settlement); this.reservations = this.reservations.filter(item => item.id !== reservation.id); delete this.journeys[founder.id]; this.movements.delete(founder.id); this.world.addEffect(home.position, 'settlementTransform', { duration: 6, settlementName: settlement.name, message: `È nato un nuovo insediamento su Elysia. Fondato da ${founder.name}.` }); this.world.diagnostics.trace('newSettlementCreated', { settlementId, founderId: founder.id }); this.world.rivalAttack?.notifySettlementRegistered(settlement); return settlement; }
  cancel(reservation) { const source=this.world.waterSources.find(item=>item.reservedByFoundingId===reservation.id); if(source)source.reservedByFoundingId=null; this.reservations = this.reservations.filter(item => item.id !== reservation.id); delete this.journeys[reservation.founderId]; return false; }
  toJSON() { return { reservations: this.reservations.map(item => ({ ...item, position: { ...item.position }, memberIds: [...item.memberIds] })), journeys: { ...this.journeys } }; }
}
