import { Config } from '../core/Config.js';
import { WorldTypeId } from '../data/WorldTypes.js';
import { Character } from '../entities/Character.js';
import { CharacterCreator } from '../entities/CharacterCreator.js';
import { CharacterMovement } from '../entities/CharacterMovement.js';
import { NameGenerator } from '../entities/NameGenerator.js';
import { Pathfinder } from '../world/Pathfinder.js';
import { House } from '../entities/House.js';
import { Household } from '../households/Household.js';
import { Dwelling } from '../entities/Dwelling.js';

export class NewcomerSystem {
  static Speech = 'Ciao, sono stanco di stare solo. Posso unirmi al vostro villaggio?';
  constructor(world, data = {}) { this.world = world; this.lastArrivalCycle = data.lastArrivalCycle ?? 1; this.pendingArrivalCycle = data.pendingArrivalCycle ?? null; this.pendingIds = [...(data.pendingIds ?? [])]; this.progress = { ...(data.progress ?? {}) }; this.movements = new Map(); this.newcomersCreated = data.newcomersCreated ?? 0; }
  processCompletedDay(cycle) { if (cycle <= this.lastArrivalCycle || cycle === this.pendingArrivalCycle) return null; this.world.diagnostics.trace('NEWCOMER_DAY_TRIGGER', { cycle }); if (this.world.characters.filter(c => c.alive).length >= Config.POPULATION_LIMIT) { this.lastArrivalCycle = cycle; this.world.addEffect(this.world.hut?.position ?? {x:0,y:0}, 'populationLimit'); return null; } this.pendingArrivalCycle = cycle; return this.attemptPendingArrival(); }
  attemptPendingArrival() { if (this.pendingArrivalCycle === null) return null; const newcomer = this.spawn(this.pendingArrivalCycle); if (newcomer) { this.lastArrivalCycle = this.pendingArrivalCycle; this.pendingArrivalCycle = null; } return newcomer; }
  spawn(cycle) { this.world.diagnostics.trace('NEWCOMER_SPAWN_ATTEMPT', { cycle }); const settlement = this.world.settlementProgression.ensureFoundingSettlement(); if (!settlement) { this.world.diagnostics.trace('NEWCOMER_SPAWN_FAILED', { cycle, reason: 'no Settlement' }); return null; } const origin = settlement.center ?? this.world.findHome(settlement.foundingHomeId)?.position; const position = origin && this.world.findEdgeReachablePosition(origin); if (!position) { this.world.diagnostics.trace('NEWCOMER_SPAWN_FAILED', { cycle, reason: 'no reachable edge position' }); return null; } const id = `newcomer-${cycle}-${this.world.nextCharacterId++}`; const name = new NameGenerator(this.world.characters.map(c => c.name)).generate(this.world.worldSeed + cycle + this.world.nextCharacterId); const base = { id, name, position, arrivalPosition: position, worldType: this.world.worldType, chosenOne: false, lifeStage: 'adult', alive: true, arrivalCycle: cycle, newcomer: true, settlementId: settlement.id, speechText: NewcomerSystem.Speech };
    let character; if (this.world.worldType === WorldTypeId.BEAST) { const species = CharacterCreator.BeastSpecies[(cycle + this.world.nextCharacterId) % CharacterCreator.BeastSpecies.length]; character = new Character({ ...base, species, reproductiveSex: cycle % 2 ? 'female' : 'male' }); } else character = new Character({ ...base, sexCharacteristics: CharacterCreator.SexCharacteristics[cycle % 3], genderIdentity: CharacterCreator.GenderIdentities[(cycle + 1) % 3], sexualOrientation: CharacterCreator.SexualOrientations[(cycle + 2) % 3] });
    this.world.addCharacter(character, false); this.pendingIds.push(id); this.newcomersCreated += 1; this.world.diagnostics.trace('NEWCOMER_CREATED', { characterId: id, cycle, position }); this.progress[id] = { wood: 0, elapsed: 0, arrived: false }; const movement = new CharacterMovement(character); movement.follow(new Pathfinder().findPath(this.world.terrain, position, origin)); this.movements.set(id, movement); character.visualState = 'walk'; return character; }
  update(deltaTime) { this.attemptPendingArrival(); for (const id of [...this.pendingIds]) { const character = this.world.characters.find(item => item.id === id); const state = this.progress[id]; if (!character || !state) continue; if (!state.arrived) { const movement = this.movements.get(id); if (!movement) { const target = this.world.settlements[0]?.center ?? this.world.hut.position; const restored = new CharacterMovement(character); restored.follow(new Pathfinder().findPath(this.world.terrain, character.position, target)); this.movements.set(id, restored); } if (this.movements.get(id).update(deltaTime)) { state.arrived = true; character.visualState = 'idle'; character.speechRemaining = 4.2; } continue; } state.elapsed += deltaTime; character.speechRemaining = Math.max(0, (character.speechRemaining ?? 0) - deltaTime); if (state.elapsed >= 1 && state.wood < Config.NEW_HOME_WOOD_COST) { state.elapsed = 0; state.wood += 1; character.aiTask = 'gatherWood'; } if (state.wood >= Config.NEW_HOME_WOOD_COST) this.establishHome(character); } }
  establishHome(character) { const settlement = this.world.settlements[0]; const vacant = this.world.homes.find(home => home.occupancy === 'vacant' && home.completed); const home = vacant ?? this.buildHome(character, settlement); if (!home) return false; const household = new Household({ id: `household-${this.world.households.length + 1}`, memberIds: [character.id], homeBuildingId: home.id, settlementId: settlement.id }); home.householdId = household.id; home.occupancy = 'occupied'; character.householdId = household.id; character.homeBuildingId = home.id; settlement.addHousehold(household.id); settlement.addHome(home.id); this.world.households.push(household); this.world.ensureAI(character); this.pendingIds = this.pendingIds.filter(id => id !== character.id); delete this.progress[character.id]; this.movements.delete(character.id); this.world.settlementProgression.evaluate(); return home; }
  buildHome(character, settlement) { const position = this.world.findSettlementHomePosition(settlement); if (!position) return null; const home = new House({ id: `home-${this.world.nextEntityId++}`, position, completed: true, visualVariant: Dwelling.variant(this.world.worldType, true, character.species), settlementId: settlement.id, occupancy: 'occupied' }); this.world.homes.push(home); this.world.addEffect(position, 'transform'); return home; }
  toJSON() { return { lastArrivalCycle: this.lastArrivalCycle, pendingArrivalCycle: this.pendingArrivalCycle, newcomersCreated: this.newcomersCreated, pendingIds: [...this.pendingIds], progress: { ...this.progress } }; }
}
