import { Config } from '../core/Config.js';
import { WorldTypeId } from '../data/WorldTypes.js';
import { MigrationNarrative } from '../data/MigrationNarrative.js';
import { Character } from '../entities/Character.js';
import { CharacterCreator } from '../entities/CharacterCreator.js';
import { CharacterMovement } from '../entities/CharacterMovement.js';
import { NameGenerator } from '../entities/NameGenerator.js';
import { Pathfinder } from '../world/Pathfinder.js';
import { House } from '../entities/House.js';
import { Household } from '../households/Household.js';
import { Dwelling } from '../entities/Dwelling.js';
import { SettlementRules } from './SettlementRules.js';

export class NewcomerSystem {
  static Speech = 'Ciao, sono stanco di stare solo. Posso unirmi al vostro villaggio?';
  static BeastSpeech = 'Ho seguito il profumo della vita fino a Elysia. Posso restare?';
  constructor(world, data = {}) { this.world = world; this.lastArrivalCycle = data.lastArrivalCycle ?? 1; this.pendingArrivalCycle = data.pendingArrivalCycle ?? null; this.pendingIds = [...(data.pendingIds ?? [])]; this.progress = { ...(data.progress ?? {}) }; this.movements = new Map(); this.newcomersCreated = data.newcomersCreated ?? 0; this.narrative = new MigrationNarrative(data.narrative); }
  processCompletedDay(cycle) { if (cycle <= this.lastArrivalCycle || cycle === this.pendingArrivalCycle) return null; this.world.diagnostics.trace('NEWCOMER_DAY_TRIGGER', { cycle }); if (this.world.characters.filter(character => character.alive).length >= Config.POPULATION_LIMIT) { this.lastArrivalCycle = cycle; return null; } this.pendingArrivalCycle = cycle; return this.attemptPendingArrival(); }
  attemptPendingArrival() { if (this.pendingArrivalCycle === null) return null; const newcomer = this.spawn(this.pendingArrivalCycle); if (newcomer || !this.eligibleSettlements().length) { this.lastArrivalCycle = this.pendingArrivalCycle; this.pendingArrivalCycle = null; } return newcomer; }
  eligibleSettlements() { return this.world.settlements.filter(settlement => SettlementRules.canReceiveExternalArrival(settlement) && !this.pendingIds.some(id => this.world.characters.find(character => character.id === id)?.settlementId === settlement.id)); }
  spawn(cycle) {
    this.world.settlementProgression.ensureFoundingSettlement();
    const eligible = this.eligibleSettlements(); const settlement = eligible[Math.abs(cycle) % Math.max(1, eligible.length)];
    if (!settlement) return null;
    const target = settlement.center ?? this.world.findHome(settlement.foundingHomeId)?.position; const position = target && this.world.findEdgeReachablePosition(target); if (!position) return null;
    const id = `newcomer-${cycle}-${this.world.nextCharacterId++}`; const seed = this.world.worldSeed + cycle + this.world.nextCharacterId; const originWorld = this.narrative.origin(seed); const arrivalStoryType = this.narrative.story(seed + 3); const species = this.world.worldType === WorldTypeId.BEAST ? CharacterCreator.BeastSpecies[Math.abs(seed) % CharacterCreator.BeastSpecies.length] : null; const dialogue = this.narrative.dialogue(arrivalStoryType, originWorld, species, seed + 7);
    const base = { id, name: new NameGenerator(this.world.characters.map(character => character.name)).generate(seed), position, arrivalPosition: position, worldType: this.world.worldType, chosenOne: false, lifeStage: 'adult', alive: true, arrivalCycle: cycle, newcomer: true, introductionCompleted: false, settlementId: settlement.id, originWorld, arrivalStoryType, arrivalLineId: dialogue.id, speechText: dialogue.lines[0], speechLines: dialogue.lines };
    const character = species ? new Character({ ...base, species, reproductiveSex: cycle % 2 ? 'female' : 'male' }) : new Character({ ...base, sexCharacteristics: CharacterCreator.SexCharacteristics[cycle % 3], genderIdentity: CharacterCreator.GenderIdentities[(cycle + 1) % 3], sexualOrientation: CharacterCreator.SexualOrientations[(cycle + 2) % 3] });
    this.world.addCharacter(character, false); settlement.externalArrivalCount += 1; this.pendingIds.push(id); this.newcomersCreated += 1; this.progress[id] = { wood: 0, elapsed: 0, stage: 'approaching', speechRemaining: 0, speechIndex: 0 };
    const movement = new CharacterMovement(character); movement.follow(new Pathfinder().findPath(this.world.terrain, position, target).slice(0, -3)); this.movements.set(id, movement); character.visualState = 'walk';
    this.world.diagnostics.trace('newcomerIntroductionStarted', { characterId: id }); this.world.diagnostics.trace('externalMigrantGenerated', { characterId: id, settlementId: settlement.id }); this.world.diagnostics.trace('externalMigrantOriginAssigned', { characterId: id, originWorld }); this.world.diagnostics.trace('migrationStoryAssigned', { characterId: id, arrivalStoryType }); if (settlement.externalArrivalCount === Config.MAX_EXTERNAL_ARRIVALS) this.world.diagnostics.trace('settlementExternalCapReached', { settlementId: settlement.id });
    return character;
  }
  update(deltaTime) { this.attemptPendingArrival(); for (const id of [...this.pendingIds]) this.updateNewcomer(id, deltaTime); }
  updateNewcomer(id, deltaTime) {
    const character = this.world.characters.find(item => item.id === id); const state = this.progress[id]; if (!character || !state) return;
    if (state.stage === 'approaching') { let movement = this.movements.get(id); if (!movement) { const target = this.world.settlements.find(item => item.id === character.settlementId)?.center; movement = new CharacterMovement(character); movement.follow(new Pathfinder().findPath(this.world.terrain, character.position, target).slice(0, -3)); this.movements.set(id, movement); } if (movement.update(deltaTime)) { state.stage = 'speaking'; character.visualState = 'idle'; character.aiTask = 'introducing'; this.showSpeech(character, state); this.world.diagnostics.trace('newcomerDialogueStarted', { characterId: id }); this.world.diagnostics.trace('newcomerSpeechShown', { characterId: id, speechText: character.speechText }); } return; }
    if (state.stage === 'speaking') { state.speechRemaining = Math.max(0, state.speechRemaining - deltaTime); character.speechRemaining = state.speechRemaining; if (state.speechRemaining > 0) return; const lines = character.speechLines ?? [character.speechText]; if (++state.speechIndex < lines.length) { character.speechText = lines[state.speechIndex]; this.showSpeech(character, state); return; } state.stage = 'progressing'; character.aiTask = null; character.introductionCompleted = true; this.world.diagnostics.trace('newcomerDialogueCompleted', { characterId: id }); this.world.diagnostics.trace('newcomerIntroductionCompleted', { characterId: id }); }
    state.elapsed += deltaTime; if (state.elapsed >= 1 && state.wood < Config.NEW_HOME_WOOD_COST) { state.elapsed = 0; state.wood += 1; character.aiTask = 'gatherWood'; } if (state.wood >= Config.NEW_HOME_WOOD_COST) this.establishHome(character);
  }
  showSpeech(character, state) { state.speechRemaining = Math.min(9, Math.max(Config.NEWCOMER_SPEECH_DURATION_SECONDS, character.speechText.length / 13)); character.speechRemaining = state.speechRemaining; }
  establishHome(character) { const settlement = this.world.settlements.find(item => item.id === character.settlementId); if (!settlement) return false; const vacant = this.world.homes.find(home => home.settlementId === settlement.id && home.occupancy === 'vacant' && home.completed && home.kind !== 'centralStructure'); const home = vacant ?? this.buildHome(character, settlement); if (!home) return false; const household = new Household({ id: `household-${this.world.households.length + 1}`, memberIds: [character.id], homeBuildingId: home.id, settlementId: settlement.id }); home.householdId = household.id; home.occupancy = 'occupied'; character.householdId = household.id; character.homeBuildingId = home.id; settlement.addHousehold(household.id); settlement.addHome(home.id); this.world.households.push(household); this.world.ensureAI(character); this.pendingIds = this.pendingIds.filter(id => id !== character.id); delete this.progress[character.id]; this.movements.delete(character.id); this.world.settlementProgression.evaluate(); return home; }
  buildHome(character, settlement) { if (!SettlementRules.canConstructOrdinaryHome(settlement)) return null; const position = this.world.findSettlementHomePosition(settlement, character.id); if (!position) return null; const home = new House({ id: `home-${this.world.nextEntityId++}`, position, completed: true, visualVariant: Dwelling.variant(this.world.worldType, true, character.species), settlementId: settlement.id, occupancy: 'occupied' }); this.world.homes.push(home); this.world.homePlacement.complete(character.id, home.id); this.world.addEffect(position, 'transform'); return home; }
  toJSON() { return { lastArrivalCycle: this.lastArrivalCycle, pendingArrivalCycle: this.pendingArrivalCycle, newcomersCreated: this.newcomersCreated, pendingIds: [...this.pendingIds], progress: { ...this.progress }, narrative: this.narrative.toJSON() }; }
}
