import { Config } from '../core/Config.js';
import { WorldTypeId } from '../data/WorldTypes.js';
import { CentralStructure } from '../entities/CentralStructure.js';
import { Settlement } from './Settlement.js';
import { SettlementNameGenerator } from './SettlementNameGenerator.js';

export class SettlementProgression {
  constructor(world, data = {}) { this.world = world; this.transformations = data.transformations ?? 0; }
  ensureFoundingSettlement() { if (this.world.worldType === WorldTypeId.PLANT) return null; if (this.world.settlements.length) return this.world.settlements[0]; const chosen = this.world.characters.find(character => character.chosenOne && character.alive); const household = this.world.households.find(item => item.id === chosen?.householdId) ?? this.world.households[0]; const home = this.world.findHome(household?.homeBuildingId); if (!household || !home?.completed) return null; const settlement = new Settlement({ id: 'settlement-1', name: new SettlementNameGenerator().generate(this.world.worldSeed), founderId: chosen?.id ?? household.memberIds[0], householdIds: [household.id], homeBuildingIds: [home.id], foundingHomeId: home.id, center: home.position }); household.settlementId = settlement.id; home.settlementId = settlement.id; for (const id of household.memberIds) { const character = this.world.characters.find(item => item.id === id); if (character) character.settlementId = settlement.id; } this.world.settlements.push(settlement); return settlement; }
  evaluate() { this.ensureFoundingSettlement(); let result = false; for (const settlement of this.world.settlements) result = this.evaluateSettlement(settlement) || result; return result; }
  evaluateSettlement(settlement) { if (!settlement?.isGrowing()) return false; const completed = settlement.homeBuildingIds.map(id => this.world.findHome(id)).filter(home => home?.completed && home.alive && home.kind !== 'centralStructure').length; if (completed < Config.SETTLEMENT_HOME_MILESTONE) return false; const founding = this.world.findHome(settlement.foundingHomeId); if (!founding?.completed || !founding.alive) return false; const beast = this.world.worldType === WorldTypeId.BEAST; const central = new CentralStructure({ ...founding.toJSON(), id: founding.id, settlementId: settlement.id, householdId: founding.householdId, centralVariant: beast ? 'greatDen' : 'castle', visualVariant: beast ? 'greatDen' : 'castle', placementBounds: undefined, interactionBounds: undefined, transformationAge: 0 }); const index = this.world.homes.findIndex(home => home.id === founding.id); this.world.homes[index] = central; if (this.world.hut?.id === founding.id) this.world.hut = central; settlement.centralStructureId = central.id; settlement.establish(); settlement.center = { ...central.position }; settlement.name ??= new SettlementNameGenerator().generate(this.world.worldSeed + this.transformations); this.transformations += 1; const message = beast ? 'Il grande rifugio è compiuto. L’insediamento è ora stabilito.' : 'Il Castello è compiuto. L’insediamento è ora stabilito.'; this.world.addEffect(central.position, 'settlementTransform', { duration: 5, settlementName: settlement.name, message }); this.world.diagnostics.trace('settlementImmigrationClosed', { settlementId: settlement.id, externalArrivalCount: settlement.externalArrivalCount }); this.world.diagnostics.trace('centralTransformationCompleted', { settlementId: settlement.id, buildingId: central.id, variant: central.centralVariant }); return central; }
  toJSON() { return { transformations: this.transformations }; }
}
