import { Config } from '../core/Config.js';
import { WorldTypeId } from '../data/WorldTypes.js';
import { CentralStructure } from '../entities/CentralStructure.js';
import { Settlement } from './Settlement.js';
import { SettlementNameGenerator } from './SettlementNameGenerator.js';

export class SettlementProgression {
  constructor(world, data = {}) { this.world = world; this.transformations = data.transformations ?? 0; }
  ensureFoundingSettlement() { if (this.world.worldType === WorldTypeId.PLANT) return null; if (this.world.settlements.length) return this.world.settlements[0]; const chosen = this.world.characters.find(character => character.chosenOne && character.alive); const household = this.world.households.find(item => item.id === chosen?.householdId) ?? this.world.households[0]; const home = this.world.findHome(household?.homeBuildingId); if (!household || !home?.completed) return null; const settlement = new Settlement({ id: 'settlement-1', householdIds: [household.id], homeBuildingIds: [home.id], foundingHomeId: home.id, center: home.position }); household.settlementId = settlement.id; home.settlementId = settlement.id; this.world.settlements.push(settlement); return settlement; }
  evaluate() { const settlement = this.ensureFoundingSettlement(); if (!settlement || settlement.transformed) return false; const completed = settlement.homeBuildingIds.map(id => this.world.findHome(id)).filter(home => home?.completed && home.alive && home.kind !== 'centralStructure').length; this.world.diagnostics.trace('settlementCompletedHomeCount', { settlementId: settlement.id, count: completed }); if (completed < Config.SETTLEMENT_HOME_MILESTONE) return false; const founding = this.world.findHome(settlement.foundingHomeId); if (!founding?.completed || !founding.alive) return false; this.world.diagnostics.trace('centralTransformationTriggered', { settlementId: settlement.id, completedHomeCount: completed }); const beast = this.world.worldType === WorldTypeId.BEAST; const central = new CentralStructure({ ...founding.toJSON(), id: founding.id, settlementId: settlement.id, householdId: founding.householdId, centralVariant: beast ? 'greatDen' : 'castle', visualVariant: beast ? 'greatDen' : 'castle', placementBounds: undefined, interactionBounds: undefined, transformationAge: 0 }); const index = this.world.homes.findIndex(home => home.id === founding.id); this.world.homes[index] = central; if (this.world.hut?.id === founding.id) this.world.hut = central; settlement.centralStructureId = central.id; settlement.transformed = true; settlement.center = { ...central.position }; settlement.name ??= new SettlementNameGenerator().generate(this.world.worldSeed + this.transformations); this.transformations += 1; const message = beast ? 'Il branco ha creato il suo primo grande rifugio.' : 'Il villaggio è cresciuto. È nato il primo Castello di Elysia.'; this.world.addEffect(central.position, 'settlementTransform', { duration: 5, settlementName: settlement.name, message }); this.world.diagnostics.trace('centralTransformationCompleted', { settlementId: settlement.id, buildingId: central.id, variant: central.centralVariant }); return central; }
  toJSON() { return { transformations: this.transformations }; }
}
