import { Config } from '../core/Config.js';
import { WorldTypeId } from '../data/WorldTypes.js';
import { CentralStructure } from '../entities/CentralStructure.js';
import { Settlement } from './Settlement.js';
import { SettlementNameGenerator } from './SettlementNameGenerator.js';

export class SettlementProgression {
  constructor(world, data = {}) { this.world = world; this.transformations = data.transformations ?? 0; }
  ensureFoundingSettlement() { if (this.world.worldType === WorldTypeId.PLANT || !this.world.hut?.completed || !this.world.households.length) return null; if (this.world.settlements.length) return this.world.settlements[0]; const household = this.world.households[0]; const settlement = new Settlement({ id: 'settlement-1', householdIds: [household.id], homeBuildingIds: [this.world.hut.id], foundingHomeId: this.world.hut.id, center: this.world.hut.position }); household.settlementId = settlement.id; this.world.hut.settlementId = settlement.id; this.world.homes = [this.world.hut]; this.world.settlements.push(settlement); return settlement; }
  evaluate() { const settlement = this.ensureFoundingSettlement(); if (!settlement || settlement.transformed) return false; const completed = settlement.homeBuildingIds.map(id => this.world.findHome(id)).filter(home => home?.completed && home.alive).length; if (completed < Config.SETTLEMENT_HOME_MILESTONE) return false; const founding = this.world.findHome(settlement.foundingHomeId); if (!founding) return false; const central = new CentralStructure({ ...founding.toJSON(), id: founding.id, settlementId: settlement.id, householdId: founding.householdId, centralVariant: this.world.worldType === WorldTypeId.BEAST ? 'greatDen' : 'castle', visualVariant: this.world.worldType === WorldTypeId.BEAST ? 'greatDen' : 'castle', transformationAge: 0 }); const index = this.world.homes.findIndex(home => home.id === founding.id); this.world.homes[index] = central; if (this.world.hut?.id === founding.id) this.world.hut = central; settlement.centralStructureId = central.id; settlement.transformed = true; settlement.name = new SettlementNameGenerator().generate(this.world.worldSeed + this.transformations); this.transformations += 1; this.world.addEffect(central.position, 'settlementTransform', { settlementName: settlement.name, message: 'Non sono più soltanto esseri che sopravvivono. Hanno creato un luogo a cui appartenere.' }); return central; }
  toJSON() { return { transformations: this.transformations }; }
}
