export class CombatSystem {
  constructor(world) { this.world=world; }
  validTargets() { return this.world.characters.filter(c=>c.alive&&!c.insideHome); }
  updateDefenders(dt) { for(const character of this.validTargets()){character.combatCooldown=Math.max(0,(character.combatCooldown??0)-dt);const enemy=this.world.invasions.enemies.filter(e=>e.alive).sort((a,b)=>Math.hypot(a.position.x-character.position.x,a.position.y-character.position.y)-Math.hypot(b.position.x-character.position.x,b.position.y-character.position.y))[0];if(!enemy)continue;if(character.lifeStage==='child'||!character.isArmed){const home=this.world.homeFor(character);if(home&&Math.hypot(home.position.x-character.position.x,home.position.y-character.position.y)<1.2)character.insideHome=true;continue;}const d=Math.hypot(enemy.position.x-character.position.x,enemy.position.y-character.position.y);if(d>1.5){const dx=(enemy.position.x-character.position.x)/d,dy=(enemy.position.y-character.position.y)/d;const next={x:character.position.x+dx*dt*1.8,y:character.position.y+dy*dt*1.8};if(this.world.isWalkable(next.x,next.y))character.position=next;}else if(!character.combatCooldown){enemy.takeDamage(16);character.combatCooldown=1.4;}} }
  nearestTarget(enemy) { return this.validTargets().sort((a,b)=>Math.hypot(a.position.x-enemy.position.x,a.position.y-enemy.position.y)-Math.hypot(b.position.x-enemy.position.x,b.position.y-enemy.position.y))[0] ?? null; }
  updateEnemy(enemy,dt) { const type=enemy.type;enemy.animationTime+=dt;enemy.cooldownRemaining=Math.max(0,enemy.cooldownRemaining-dt);let target=this.world.characters.find(c=>c.id===enemy.targetId&&c.alive&&!c.insideHome)??this.nearestTarget(enemy);enemy.targetId=target?.id??null;if(!target)return;const dx=target.position.x-enemy.position.x,dy=target.position.y-enemy.position.y,d=Math.hypot(dx,dy)||.001;enemy.facing=dx<0?-1:1;
    if(type.minimumRange&&d<type.minimumRange){this.move(enemy,-dx/d,-dy/d,type.speed*dt);enemy.attackPhase='reposition';return;}
    if(d>type.range){this.move(enemy,dx/d,dy/d,type.speed*dt);enemy.attackPhase='pursue';return;}
    if(enemy.cooldownRemaining>0){enemy.attackPhase='idle';return;} enemy.attackElapsed+=dt;const progress=enemy.attackElapsed/type.windup;enemy.attackPhase=type.id==='lionArcher'?(progress<.3?'raise':progress<.72?'draw':'aim'):type.id==='dolphinGunner'?'charge':'thrust';if(enemy.attackElapsed>=type.windup){this.deliver(enemy,target);enemy.attackElapsed=0;enemy.cooldownRemaining=type.attackCooldown;enemy.attackPhase='release';} }
  move(enemy,x,y,distance){const next={x:enemy.position.x+x*distance,y:enemy.position.y+y*distance};if(this.world.isWalkable(next.x,next.y))enemy.position=next;}
  deliver(enemy,target){const type=enemy.type;if(type.deliveryType==='melee'){if(Math.hypot(enemy.position.x-target.position.x,enemy.position.y-target.position.y)<=type.range)this.applyDamage(target,type.damage,'melee');return null;}return this.world.projectiles.create(type.projectileType,enemy,target,type.damage,type.projectileSpeed);}
  applyDamage(target,damage,impactType='melee'){if(!target?.alive)return false;if(target.hasDivineShield||target.hasShield){target.hasShield=false;target.shieldImpactReaction=1;this.world.addEffect(target.position,impactType==='energyBolt'?'energyShieldImpact':'shieldImpact');return false;}target.health=target.health??100;target.health=Math.max(0,target.health-damage);if(!target.health)this.world.killCharacter(target);return true;}
}
