import test from 'node:test'; import assert from 'node:assert/strict';
import { World } from '../src/world/World.js'; import { Miracles } from '../src/miracles/Miracles.js'; import { Character } from '../src/entities/Character.js'; import { Config } from '../src/core/Config.js';
const setup=(type='human')=>{const w=new World();w.create(type,909);const p=w.findSpawnPosition();const c=new Character({id:'c',name:'Eli',position:p,worldType:type,chosenOne:true,sexCharacteristics:'female',genderIdentity:'woman',sexualOrientation:'bisexual'});w.addCharacter(c);return {w,c,m:new Miracles(w)};};
test('Flower is gameplay state and matures exactly after a complete cycle',()=>{const {w,m}=setup();const p=w.findBuildPosition(w.characters[0].position);assert.ok(m.cast('flower',p));assert.equal(w.flowers.length,1);w.update(Config.WORLD_CYCLE_SECONDS-.01);assert.equal(w.flowers.length,1);w.update(.02);assert.equal(w.flowers.length,0);assert.equal(w.appleTrees.length,1);assert.equal(w.appleTrees[0].harvest(0),1);assert.equal(w.appleTrees[0].alive,true);assert.equal(w.appleTrees[0].harvest(0),0);});
test('Lightning kills on third even through Shield and Blessing exalts on fifth',()=>{const {w,c,m}=setup();m.cast('shield',c.position);assert.equal(c.hasShield,true);m.cast('lightning',c.position);m.cast('lightning',c.position);assert.equal(c.alive,true);m.cast('lightning',c.position);assert.equal(c.lightningStrikeCount,3);assert.equal(c.alive,false);const second=new Character({...c.toJSON(),id:'b',alive:true,lightningStrikeCount:0,position:{x:c.position.x+2,y:c.position.y}});w.addCharacter(second);for(let i=0;i<5;i++)m.cast('blessing',second.position);assert.equal(second.isExalted,true);assert.equal(second.canFoundSettlement,true);});
test('character powers preserve identity, arm and protect without combat',()=>{const {c,m}=setup();const partner={id:'partner'};c.partnerId=partner.id;const parents=['p1','p2'];c.parentIds=parents;m.cast('changeSex',c.position,'intersex');m.cast('giveWeapons',c.position);m.cast('shield',c.position);assert.equal(c.sexCharacteristics,'intersex');assert.equal(c.genderIdentity,'woman');assert.equal(c.sexualOrientation,'bisexual');assert.equal(c.partnerId,'partner');assert.deepEqual(c.parentIds,parents);assert.equal(c.isArmed,true);assert.equal(c.hasShield,true);});
test('Ray rallies living characters with navigation and excludes dead',()=>{const {w,c,m}=setup('beast');const dead=new Character({...c.toJSON(),id:'dead',alive:false,position:{x:c.position.x+1,y:c.position.y}});w.addCharacter(dead);const target=w.findBuildPosition(c.position);assert.ok(m.cast('rayOfLight',target));assert.equal(w.ais.get(c.id).task,'divineRally');assert.notEqual(w.ais.get(dead.id).task,'divineRally');});

const establishCouple = () => {
  const { w, c: first } = setup();
  const second = new Character({ id:'partner', name:'Marco', position:{...first.position}, worldType:'human', chosenOne:false, sexCharacteristics:'male', genderIdentity:'man', sexualOrientation:'bisexual' });
  w.addCharacter(second); w.beginHut(w.findBuildPosition(first.position)); w.completeHut();
  const home=w.hut; const household={id:'household-test',memberIds:[first.id,second.id],homeBuildingId:home.id,addMember(id){if(!this.memberIds.includes(id))this.memberIds.push(id);},removeMember(id){this.memberIds=this.memberIds.filter(item=>item!==id);},toJSON(){return {...this,addMember:undefined,removeMember:undefined,toJSON:undefined};}};
  w.households=[household]; home.householdId=household.id; home.occupancy='occupied';
  for(const character of [first,second]){character.householdId=household.id;character.homeBuildingId=home.id;character.insideHome=true;} first.partnerId=second.id;second.partnerId=first.id;w.reproduction.beginRelationship(first,second);
  return {w,first,second,household,home};
};
test('death removes current occupancy, preserves partnership history and enables remarriage',()=>{const {w,first,second,household}=establishCouple();const child=new Character({id:'existing-child',name:'Child',position:first.position,worldType:'human',chosenOne:false,lifeStage:'child',parentIds:[first.id,second.id],householdId:household.id,homeBuildingId:w.hut.id});w.addCharacter(child);household.addMember(child.id);w.killCharacter(second);assert.equal(second.alive,false);assert.ok(!household.memberIds.includes(second.id));assert.equal(first.partnerId,null);assert.ok(first.formerPartnerIds.includes(second.id));assert.ok(second.formerPartnerIds.includes(first.id));const replacement=new Character({id:'replacement',name:'Luca',position:first.position,worldType:'human',chosenOne:false,sexCharacteristics:'male',genderIdentity:'man',sexualOrientation:'bisexual',householdId:household.id,homeBuildingId:w.hut.id});w.addCharacter(replacement);household.addMember(replacement.id);assert.equal(w.relationships.formCouple(first,replacement),true);assert.deepEqual(child.parentIds,[first.id,second.id]);assert.ok(household.memberIds.includes(replacement.id));assert.ok(!household.memberIds.includes(second.id));assert.equal(w.reproduction.relationships[w.reproduction.relationshipId(first,replacement)].intimacySinceLastBirth,0);});
test('remarriage still rejects incompatible and close-family candidates',()=>{const {w,first,second,household}=establishCouple();w.killCharacter(second);const incompatible=new Character({id:'straight-woman',name:'Ada',position:first.position,worldType:'human',chosenOne:false,sexCharacteristics:'female',genderIdentity:'woman',sexualOrientation:'heterosexual',householdId:household.id,homeBuildingId:w.hut.id});assert.equal(w.relationships.compatible(first,incompatible),false);const child=new Character({id:'adult-child',name:'Child',position:first.position,worldType:'human',chosenOne:false,lifeStage:'adult',parentIds:[first.id,second.id],sexCharacteristics:'male',genderIdentity:'man',sexualOrientation:'bisexual',householdId:household.id,homeBuildingId:w.hut.id});assert.equal(w.relationships.compatible(first,child),false);});
test('nightly intimacy happens once, persists failures, and guarantees the third new life',()=>{const {w,first,second}=establishCouple();w.reproduction.random.next=()=>.99;const id=w.reproduction.relationshipId(first,second);assert.equal(w.reproduction.evaluateNight(1),true);assert.equal(w.reproduction.relationships[id].intimacySinceLastBirth,1);assert.equal(w.effects.filter(e=>e.type==='intimacy').length,1);assert.equal(w.reproduction.evaluateNight(1),false);assert.equal(w.effects.filter(e=>e.type==='intimacy').length,1);w.reproduction.evaluateNight(2);assert.equal(w.reproduction.relationships[id].intimacySinceLastBirth,2);assert.equal(w.reproduction.pendingBirths.length,0);w.reproduction.evaluateNight(3);assert.equal(w.reproduction.relationships[id].intimacySinceLastBirth,0);assert.equal(w.reproduction.pendingBirths.length,1);assert.equal(w.effects.some(e=>e.type==='newLife'),false);const child=w.reproduction.birthAtDawn(4);assert.ok(child);assert.deepEqual(child.parentIds,[first.id,second.id]);assert.equal(w.effects.find(e=>e.type==='newLife').message,"La nuova vita nasce dal legame tra due esseri, l'amore invoca un briciolo del tuo potere anche senza la tua volontà.");});
test('first or second intimacy may conceive and save restores progression without duplicate events',()=>{for(const successNight of [1,2]){const {w}=establishCouple();let rolls=0;w.reproduction.random.next=()=>++rolls===successNight?0:.99;w.reproduction.evaluateNight(1);if(successNight===2)w.reproduction.evaluateNight(2);assert.equal(w.reproduction.pendingBirths.length,1);assert.equal(rolls,successNight);}const {w,first,second}=establishCouple();w.reproduction.random.next=()=>.99;w.reproduction.evaluateNight(1);const saved=w.toJSON();const restored=new World();restored.restore('human',909,null,saved);const id=restored.reproduction.relationshipId(first,second);assert.equal(restored.reproduction.relationships[id].intimacySinceLastBirth,1);assert.equal(restored.reproduction.evaluateNight(1),false);restored.reproduction.evaluateNight(2);assert.equal(restored.reproduction.relationships[id].intimacySinceLastBirth,2);});
test('intimacy visuals vary without consuming or changing the new-life roll',()=>{const {w}=establishCouple();let rolls=0;w.reproduction.random.next=()=>{rolls+=1;return .99;};w.reproduction.evaluateNight(1);w.reproduction.evaluateNight(2);assert.equal(rolls,2);const variants=w.effects.filter(effect=>effect.type==='intimacy').map(effect=>effect.visualVariant);assert.equal(new Set(variants).size,2);});
