import test from 'node:test';
import assert from 'node:assert/strict';
import { Character } from '../src/entities/Character.js';
import { BeliefSystem } from '../src/beliefs/BeliefSystem.js';
import { PersonalBeliefs } from '../src/beliefs/PersonalBeliefs.js';
import { LocalDialogueRealizer } from '../src/dialogue/LocalDialogueRealizer.js';
import { SettlementBeliefSummary } from '../src/beliefs/SettlementBeliefSummary.js';

const character = (id, extra={}) => new Character({id,name:id,position:{x:0,y:0},worldType:'human',chosenOne:false,personality:{faithDisposition:.5,curiosity:.5,sociability:.5,kindness:.5,selfishness:.5,courage:.5},...extra});
const harness = characters => { const world={characters,diagnostics:{trace(){}},relationships:{score(){return .5;}},effects:[],addEffect(position,type,data){this.effects.push({position,type,...data});}}; world.beliefSystem=new BeliefSystem(world); return world; };

test('adult faith and bounded beliefs persist without rerandomizing legacy saves',()=>{const a=character('a');const copy=new Character(a.toJSON());assert.equal(copy.faith.value,a.faith.value);assert.equal(copy.faith.level(),a.faith.level());assert.deepEqual(copy.beliefs.toJSON(),[]);});
test('ambiguous evidence stays uncertain, repeats strengthen it, and contradiction weakens it',()=>{const a=character('a');const world=harness([a]);const first=a.memories.remember({eventType:'lightning',participants:['thief'],importance:1});world.beliefSystem.observe(a,first,{beliefType:BeliefSystem.Types.THEFT,ambiguous:true});const belief=a.beliefs.get(BeliefSystem.Types.THEFT),low=belief.confidence;assert.ok(low<.4);for(let i=0;i<3;i++){const m=a.memories.remember({eventType:'lightning',participants:['thief']});world.beliefSystem.observe(a,m,{beliefType:BeliefSystem.Types.THEFT,reasonKnown:true});}assert.ok(belief.confidence>low);const before=belief.confidence,m=a.memories.remember({eventType:'blessing',participants:['thief']});world.beliefSystem.observe(a,m,{beliefType:BeliefSystem.Types.THEFT,contradicts:true,reasonKnown:true});assert.ok(belief.confidence<before);assert.ok(belief.supportingMemories.every(id=>a.memories.entries.some(memory=>memory.id===id)));});
test('knowledge remains factual while interpretation is a separate possibly wrong belief',()=>{const a=character('a');a.knowledge.learn({type:'lightning',subjectId:'b',source:'WITNESSED'});assert.equal(a.knowledge.knows('lightning','b').type,'lightning');assert.equal(a.beliefs.get(BeliefSystem.Types.THEFT),null);a.beliefs.upsert(BeliefSystem.Types.STRENGTH,.2,'memory-unknown',PersonalBeliefs.Sources.ASSUMPTION);assert.ok(a.beliefs.get(BeliefSystem.Types.STRENGTH));});
test('social teaching preserves source and supports acceptance, doubt, and rejection',()=>{const speaker=character('speaker',{isExalted:true}),listener=character('listener'),world=harness([speaker,listener]);speaker.beliefs.upsert(BeliefSystem.Types.SHARING,.8,'memory-1',PersonalBeliefs.Sources.PERSONAL_EXPERIENCE);world.relationships.score=()=>1;const accepted=world.beliefSystem.teach(speaker,listener,BeliefSystem.Types.SHARING);assert.equal(accepted.outcome,'ACCEPT');assert.equal(accepted.belief.sourceType,PersonalBeliefs.Sources.EXALTED_TEACHING);assert.ok(world.beliefSystem.teachingProbability(speaker)>world.beliefSystem.teachingProbability(listener));world.relationships.score=()=>0;listener.faith.value=0;listener.personality.faithDisposition=0;assert.equal(world.beliefSystem.teach(speaker,listener,BeliefSystem.Types.SHARING).outcome,'REJECT');});
test('dynamic realization changes certainty and can voice disagreement or direct questions',()=>{const r=new LocalDialogueRealizer(),base={intent:'EXPRESS_BELIEF',beliefType:BeliefSystem.Types.THEFT,signature:()=>''};assert.match(r.realize({...base,confidenceLevel:'LOW'}),/Forse/);assert.match(r.realize({...base,confidenceLevel:'HIGH'}),/convinto/);assert.match(r.realize({intent:'DISAGREE_BELIEF',beliefType:BeliefSystem.Types.THEFT,signature:()=>''}),/Non credo/);assert.match(r.realize({intent:'ASK_DIVINE_PURPOSE',faithLevel:'SKEPTICAL',signature:()=>''}),/Non so/);});
test('settlement trends are derived and never overwrite personal beliefs',()=>{const a=character('a',{settlementId:'one'}),b=character('b',{settlementId:'two'}),world=harness([a,b]);a.beliefs.upsert(BeliefSystem.Types.PROVIDES,.7,'m1',PersonalBeliefs.Sources.PERSONAL_EXPERIENCE);b.beliefs.upsert(BeliefSystem.Types.UNPREDICTABLE,.8,'m2',PersonalBeliefs.Sources.PERSONAL_OBSERVATION);const summary=new SettlementBeliefSummary(world);assert.equal(summary.forSettlement('one').dominant.beliefType,BeliefSystem.Types.PROVIDES);assert.equal(summary.forSettlement('two').dominant.beliefType,BeliefSystem.Types.UNPREDICTABLE);assert.equal(a.beliefs.entries.length,1);});
test('children defer mature interpretation and migrants are not automatically faithless',()=>{const child=character('child',{lifeStage:'child'}),migrant=character('migrant',{originType:'externalMigrant'}),world=harness([child,migrant]),memory=child.memories.remember({eventType:'blessing',participants:['child']});assert.equal(world.beliefSystem.observe(child,memory,{beliefType:BeliefSystem.Types.FAVORS}),null);assert.ok(migrant.faith.value>.25);});
