import test from 'node:test'; import assert from 'node:assert/strict';
import { Settlement } from '../src/settlements/Settlement.js'; import { SettlementCulture } from '../src/culture/SettlementCulture.js'; import { CultureSystem } from '../src/culture/CultureSystem.js'; import { CultureBehaviorSystem } from '../src/culture/CultureBehaviorSystem.js'; import { SocialReputation } from '../src/social/SocialReputation.js'; import { ResourceStorage } from '../src/resources/ResourceStorage.js'; import { LocalDialogueRealizer } from '../src/dialogue/LocalDialogueRealizer.js'; import { Config } from '../src/core/Config.js';
const person=(id,settlementId,homeBuildingId)=>({id,name:id,alive:true,lifeStage:'adult',settlementId,homeBuildingId,isExalted:false,personality:{kindness:.8,selfishness:.1,courage:.7,sociability:.7},faith:{value:.5},reputation:new SocialReputation(),position:{x:0,y:0}});
const world=()=>{const settlement=new Settlement({id:'s',founderId:'a'}),a=person('a','s','a'),b=person('b','s','b');const w={settlements:[settlement],characters:[a,b],simulationTime:0,worldTime:{cycle:1},diagnostics:{trace(){}},settlementBeliefs:{forSettlement(){return {population:0};}},homes:[],invasions:{enemies:[]},dialogue:{say(){}},homeFor(c){return this.homes.find(h=>h.id===c.homeBuildingId);}};w.cultures=new CultureSystem(w);return w;};
test('Alpha 1.7 version and semantic dimensions',()=>{assert.equal(Config.VERSION,'Alpha 1.7.0');assert.deepEqual(Object.keys(new SettlementCulture().dimensions),SettlementCulture.Dimensions);});
test('founder bias and repeated signals are inertial, persistent and settlement-local',()=>{const w=world(),c=w.cultures.initialize(w.settlements[0]);assert.equal(c.founderInfluence.characterId,'a');for(let i=0;i<20;i++)w.cultures.addSignal('s','cooperation');const high=c.value('COOPERATION');w.cultures.addSignal('s','theft');assert.ok(c.value('COOPERATION')>0&&c.value('COOPERATION')<high);assert.deepEqual(new Settlement({id:'s',culture:c.toJSON()}).culture.toJSON(),c.toJSON());});
test('stable culture forms probabilistic custom and exactly conserves one shared Food',()=>{const w=world(),c=w.settlements[0].culture;c.dimensions.COOPERATION=.6;c.stability.COOPERATION=8;w.cultures.refresh(w.settlements[0]);assert.ok(c.hasCustom('SHARE_FOOD_IN_CRISIS'));w.homes=[{id:'a',settlementId:'s',storage:new ResourceStorage({food:5})},{id:'b',settlementId:'s',storage:new ResourceStorage({food:0})}];const behavior=new CultureBehaviorSystem(w);assert.equal(behavior.tryShare(w.settlements[0],()=>0),true);assert.equal(w.homes[0].storage.get('food'),4);assert.equal(w.homes[1].storage.get('food'),1);assert.ok(w.cultures.probability(w.characters[0],'SHARE_FOOD_IN_CRISIS',0)<1);});
test('reputation is observer-local, supports uncertain hearsay and may be false',()=>{const a=new SocialReputation(),b=new SocialReputation();assert.deepEqual(a.labelsFor('x'),[]);a.learn('x','THIEF',{falseAccusation:true});a.share('x','THIEF',{reputation:b},'a');assert.ok(b.entries[0].certainty<1);assert.equal(b.entries[0].falseAccusation,false);});
test('dialogue realizes only supplied customs and beast-aware language',()=>{const r=new LocalDialogueRealizer();assert.match(r.EXPRESS_CUSTOM({custom:'SHARE_FOOD_IN_CRISIS'},{beast:false}),/cibo/);assert.match(r.EXPRESS_CUSTOM({custom:'SHARE_FOOD_IN_CRISIS'},{beast:true}),/branco/);});
