import test from 'node:test';
import assert from 'node:assert/strict';
import { World } from '../src/world/World.js';
import { Character } from '../src/entities/Character.js';
import { Settlement } from '../src/settlements/Settlement.js';
import { House } from '../src/entities/House.js';
import { Household } from '../src/households/Household.js';
import { Config } from '../src/core/Config.js';
import { SettlementDiplomacySystem } from '../src/diplomacy/SettlementDiplomacySystem.js';

const character=(id,position={x:48,y:30})=>new Character({id,name:id,position,worldType:'human',chosenOne:false,isExalted:true,lifeStage:'adult'});
function foundedWorld(){const world=new World();world.create('human',185);const founder=character('chosen');founder.chosenOne=true;world.addCharacter(founder);const home=new House({id:'home-1',position:{x:48,y:30},completed:true,settlementId:'settlement-1'});const household=new Household({id:'household-1',memberIds:[founder.id],homeBuildingId:home.id,settlementId:'settlement-1'});founder.householdId=household.id;founder.homeBuildingId=home.id;world.homes=[home];world.hut=home;world.households=[household];world.settlementProgression.ensureFoundingSettlement();return world;}

test('Alpha 1.8.5 identifies the stabilization milestone',()=>{assert.equal(Config.VERSION,'Alpha 1.8.5');assert.equal(Config.SETTLEMENT_HOME_MILESTONE,4);assert.equal(Config.MAX_SETTLEMENTS,3);});
test('three separated sources are supplied and the original settlement owns exactly one',()=>{const world=foundedWorld();assert.equal(world.waterSources.length,3);assert.equal(new Set(world.waterSources.map(source=>source.id)).size,3);assert.equal(world.waterSources.filter(source=>source.claimedBySettlementId==='settlement-1').length,1);assert.ok(world.settlements[0].waterSourceId);});
test('a founding reservation reserves a unique source and one Exalted cannot found twice',()=>{const world=foundedWorld(),a=character('a'),b=character('b');world.addCharacter(a);world.addCharacter(b);const first=world.exaltedFounding.begin(a),second=world.exaltedFounding.begin(b);assert.ok(first);assert.ok(second);assert.notEqual(first.waterSourceId,second.waterSourceId);world.exaltedFounding.complete(first,a);assert.equal(a.hasFoundedSettlement,true);assert.equal(world.exaltedFounding.begin(a),null);world.exaltedFounding.complete(second,b);assert.equal(world.settlements.length,3);assert.equal(world.exaltedFounding.evaluate(),null);assert.equal(new Set(world.settlements.map(item=>item.waterSourceId)).size,3);});
test('claimed and dry water never fall back to another settlement source',()=>{const world=foundedWorld(),resident=world.characters[0],own=world.settlementWater.sourceFor(resident),other=world.waterSources.find(source=>source.id!==own.id);own.dry=true;assert.equal(world.ais.get(resident.id).resourceAllowed(own,'water'),true);assert.equal(world.ais.get(resident.id).resourceAllowed(other,'water'),false);});
test('routine visits, kin visits and physical aid are closed and legacy traffic is cancelled',()=>{const world=foundedWorld();world.settlements.push(new Settlement({id:'settlement-2',center:{x:20,y:20}}));const traveler=world.characters[0];traveler.parentIds=['kin'];const diplomacy=new SettlementDiplomacySystem(world,{visits:[{id:'old',characterId:traveler.id,homeSettlementId:'settlement-1',visitorSettlementId:'settlement-2',state:'TRAVELING'}]});assert.equal(diplomacy.startVisit(traveler,'settlement-2'),null);assert.equal(diplomacy.startFamilyVisit(traveler,'settlement-2'),null);assert.equal(diplomacy.visits[0].state,'INTERRUPTED');assert.equal(traveler.visitorSettlementId,null);});
test('Castle waits for four completed Homes then absorbs all four with Households and storage intact',()=>{const world=foundedWorld(),settlement=world.settlements[0];for(let n=2;n<=4;n++){const home=new House({id:`home-${n}`,position:{x:48+n*3,y:30},completed:n<4,settlementId:settlement.id,storage:{wood:1,water:1,food:1}});world.homes.push(home);settlement.addHome(home.id);}assert.equal(world.settlementProgression.evaluateSettlement(settlement),false);world.findHome('home-4').completed=true;const central=world.settlementProgression.evaluateSettlement(settlement);assert.ok(central);assert.equal(world.homes.filter(home=>home.settlementId===settlement.id).length,1);assert.equal(settlement.state,'ESTABLISHED');assert.equal(central.storage.get('wood'),3);});
