import test from 'node:test';
import assert from 'node:assert/strict';
import { SettlementRelationship } from '../src/diplomacy/SettlementRelationship.js';
import { SettlementDiplomacySystem } from '../src/diplomacy/SettlementDiplomacySystem.js';
import { Settlement } from '../src/settlements/Settlement.js';
import { ResourceStorage } from '../src/resources/ResourceStorage.js';
import { Config } from '../src/core/Config.js';

const settlement=(id,x)=>new Settlement({id,name:id,founderId:`${id}-adult`,center:{x,y:1},foundingHomeId:`${id}-home`});
const adult=(id,s,x)=>({id,name:id,alive:true,lifeStage:'adult',settlementId:s,position:{x,y:1},parentIds:[],reputation:{entries:[]}});
const makeWorld=()=>{const settlements=[settlement('a',1),settlement('b',5),settlement('c',8)],characters=[adult('a-adult','a',1),adult('b-adult','b',5),adult('c-adult','c',8)],homes=settlements.map((s,i)=>({id:`${s.id}-home`,settlementId:s.id,storage:new ResourceStorage({food:i?0:6,water:3,wood:3},10)}));const terrain={getTerrainAt(){return'grass';},isWalkable(){return true;},width:12,height:4};return{settlements,characters,homes,terrain,worldTime:{cycle:10},diagnostics:{trace(){}},dialogue:{say(){}},findHome(id){return homes.find(h=>h.id===id);}};};

test('Alpha 1.8 version and all three independent pair records',()=>{const w=makeWorld(),d=new SettlementDiplomacySystem(w);assert.equal(Config.VERSION,'Alpha 1.8.0');assert.equal(d.relationships.length,3);d.relation('a','b').change('a',{trust:20});assert.equal(d.view('a','c').trust,0);assert.equal(d.view('b','a').trust,0);assert.equal(new SettlementDiplomacySystem(w,d.toJSON()).view('a','b').trust,20);});
test('status is dimensional, hysteretic and minor tension decays',()=>{const r=new SettlementRelationship({settlementAId:'a',settlementBId:'b'});r.change('a',{trust:80,affinity:60,cooperation:60});assert.equal(r.perception('a').statusSummary,'FRIENDLY');r.change('b',{tension:90});assert.equal(r.perception('b').statusSummary,'HOSTILE');r.perception('b').memories=[];r.decay(12);assert.ok(r.perception('b').tension<90);});
test('shortage is real, scarcity refusal is contextual and no fake request forms',()=>{const w=makeWorld(),d=new SettlementDiplomacySystem(w);assert.ok(d.requestAid('b','a','food'));assert.equal(d.requestAid('a','b','food'),null);const decision=d.decideAid({targetSettlementId:'b',requesterSettlementId:'a',resource:'food',amount:3});assert.equal(decision.outcome,'CANNOT_HELP');});
test('aid cargo is removed, physically delivered once, remembered and conserved',()=>{const w=makeWorld(),d=new SettlementDiplomacySystem(w),donor=w.homes[0].storage,recipient=w.homes[1].storage,before=donor.get('food')+recipient.get('food');const delivery=d.startAidDelivery('a','b','food',3);assert.ok(delivery);assert.equal(donor.get('food'),3);const visit=d.visits[0];for(let i=0;i<10&&visit.state==='TRAVELING';i++)d.updateVisit(visit,1);assert.equal(recipient.get('food'),3);assert.equal(donor.get('food')+recipient.get('food'),before);assert.equal(d.deliver(delivery),false);assert.equal(recipient.get('food'),3);assert.equal(d.view('b','a').memories.at(-1).type,'AID_DELIVERED');});
test('known theft creates perspective tension but unknown origin creates none',()=>{const w=makeWorld(),d=new SettlementDiplomacySystem(w),thief=w.characters[0];assert.equal(d.recordTheft({victimSettlementId:'b',thief,originKnown:false}),false);assert.equal(d.view('b','a').tension,0);assert.equal(d.recordTheft({victimSettlementId:'b',thief,originKnown:true}),true);assert.ok(d.view('b','a').tension>0);assert.equal(d.view('a','b').tension,0);});
test('visitor retains membership, family visit requires kin and cooldown prevents spam',()=>{const w=makeWorld(),d=new SettlementDiplomacySystem(w),traveler=w.characters[0];assert.equal(d.startFamilyVisit(traveler,'b'),null);traveler.parentIds=['b-adult'];const visit=d.startFamilyVisit(traveler,'b');assert.ok(visit);assert.equal(traveler.settlementId,'a');for(let i=0;i<30&&visit.state!=='COMPLETE';i++)d.updateVisit(visit,1);assert.equal(traveler.settlementId,'a');assert.equal(traveler.visitorSettlementId,null);assert.equal(d.startFamilyVisit(traveler,'b'),null);});
