import test from 'node:test';
import assert from 'node:assert/strict';
import { World } from '../src/world/World.js';
import { Config } from '../src/core/Config.js';
import { PowerManifestations } from '../src/data/PowerManifestations.js';
import { DIVINE_POWERS } from '../src/data/Powers.js';
import { Character } from '../src/entities/Character.js';
import { House } from '../src/entities/House.js';
import { Household } from '../src/households/Household.js';
import { Settlement } from '../src/settlements/Settlement.js';
import { RelationshipSystem } from '../src/relationships/RelationshipSystem.js';

const world = type => { const item=new World(); item.create(type,808); return item; };
test('food slot retains its stable id while manifestations diverge',()=>{ const power=DIVINE_POWERS[3]; assert.equal(power.id,'cow'); assert.equal(PowerManifestations.resolve(power,'human').label,'MUCCA'); assert.equal(PowerManifestations.resolve(power,'beast').label,'CIBO'); assert.notEqual(PowerManifestations.resolve(power,'beast').icon,power.icon); });
test('Human casts Cow while Beast casts finite semantic FOOD',()=>{ const human=world('human'); human.placeEntity('cow',{x:20,y:20}); assert.equal(human.cows.length,1); const beast=world('beast'); const food=beast.placeEntity('cow',{x:20,y:20}); assert.equal(beast.cows.length,0); assert.equal(beast.animalFoodSources.length,1); assert.equal(food.remainingYield,Config.ANIMAL_FOOD_YIELD); assert.deepEqual([food.collect(),food.collect(),food.collect(),food.collect()],[1,1,1,0]); assert.equal(food.alive,false); });
test('close family is excluded and Beast pairing is same species',()=>{ const base={position:{x:1,y:1},worldType:'beast',chosenOne:false,lifeStage:'adult',alive:true}; const parent=new Character({...base,id:'p',name:'P',species:'deer'}); const child=new Character({...base,id:'c',name:'C',species:'deer',parentIds:['p']}); const sibling=new Character({...base,id:'s',name:'S',species:'deer',parentIds:['p']}); const cat=new Character({...base,id:'k',name:'K',species:'cat'}); assert.equal(RelationshipSystem.isCloseFamily(parent,child),true); assert.equal(RelationshipSystem.isCloseFamily(child,sibling),true); const beast=world('beast'); assert.equal(beast.relationships.compatible(child,sibling),false); assert.equal(beast.relationships.compatible(child,cat),false); });
test('four retained homes transform founding home once and preserve storage',()=>{ const item=world('human'); const pos=item.findSpawnPosition(); const founding=new House({id:'home-1',position:pos,householdId:'hh-1',storage:{wood:4,water:5,food:3}}); item.hut=founding; item.homes=[founding]; item.households=[new Household({id:'hh-1',memberIds:['one'],homeBuildingId:'home-1',settlementId:'settlement-1'})]; item.settlements=[new Settlement({id:'settlement-1',householdIds:['hh-1'],homeBuildingIds:['home-1'],foundingHomeId:'home-1',center:pos})]; for(let n=2;n<=4;n++){const home=new House({id:`home-${n}`,position:{x:pos.x+n*3,y:pos.y},completed:true,settlementId:'settlement-1'}); item.homes.push(home); item.settlements[0].addHome(home.id);} const central=item.settlementProgression.evaluate(); assert.equal(central.centralVariant,'castle'); assert.equal(central.storage.capacity,30); assert.deepEqual(central.storage.values,{wood:4,water:5,food:3}); assert.equal(item.homes.length,4); assert.ok(item.settlements[0].name); assert.equal(item.settlementProgression.evaluate(),false); const restored=world('human'); restored.restore('human',808,null,item.toJSON()); assert.equal(restored.settlements[0].transformed,true); assert.equal(restored.settlementProgression.evaluate(),false); });
