import test from 'node:test';
import assert from 'node:assert/strict';
import { Character } from '../src/entities/Character.js';
import { RefugeeIdentity } from '../src/entities/RefugeeIdentity.js';
import { PartnerGenerator } from '../src/entities/PartnerGenerator.js';
import { CharacterCompatibility } from '../src/relationships/CharacterCompatibility.js';
import { CharacterCreator } from '../src/entities/CharacterCreator.js';
import { World } from '../src/world/World.js';
import { Hut } from '../src/entities/Hut.js';
import { Settlement } from '../src/settlements/Settlement.js';

const origins={rivalWorld1:'Varkesh',rivalWorld2:'Ilyrion',rivalWorld3:'Pelagion-9'};
function citizen(id,worldId,extra={}){const originWorld=origins[worldId];return new Character({id,name:id,position:{x:10,y:10},worldType:'human',chosenOne:false,newcomer:true,originType:'externalMigrant',originWorld,...RefugeeIdentity.data(originWorld),...extra});}
function invasionWorld(){const world=new World();world.create('human',120);world.settlements=[new Settlement({id:'s',center:world.findSpawnPosition()})];return world;}

test('Rival identity is semantic while generic migrants remain generic',()=>{for(const[id,species]of Object.entries(RefugeeIdentity.TrueSpecies)){const character=citizen(id,id);assert.equal(character.originWorldId,id);assert.equal(character.trueSpecies,species);assert.equal(character.isDisguised,true);assert.equal(character.species,undefined);assert.equal(character.factionId,'elysia');}const generic=new Character({id:'g',name:'G',position:{x:1,y:1},worldType:'human',newcomer:true,originWorld:'Asteria'});assert.equal(generic.originWorldId,null);assert.equal(generic.trueSpecies,null);});
test('matching first invasion reveals the same-world family without changing its life',()=>{const world=invasionWorld();const first=citizen('marco','rivalWorld3',{householdId:'hh',partnerId:'p',blessingCount:3,isArmed:true,hasShield:true,behaviourPreferences:{theft:.8}}),second=citizen('two','rivalWorld3'),other=citizen('lion','rivalWorld1');world.addCharacter(first);world.addCharacter(second);world.addCharacter(other);const memory=first.behaviourMemory;assert.equal(world.invasions.start('rivalWorld3',1),true);assert.equal(first.speechText,'No... loro no.');assert.equal(first.visualProfile,'civilian.dolphin');assert.equal(first.factionId,'elysia');assert.equal(first.householdId,'hh');assert.equal(first.partnerId,'p');assert.equal(first.behaviourMemory,memory);assert.equal(first.blessingCount,3);assert.equal(first.isArmed,true);assert.equal(first.hasShield,true);assert.equal(second.identityRevealed,true);assert.equal(other.isDisguised,true);});
test('all three true forms and public post-reveal arrivals are explicit',()=>{for(const worldId of Object.keys(RefugeeIdentity.TrueSpecies)){const identity=RefugeeIdentity.data(origins[worldId],true);assert.equal(identity.isDisguised,false);assert.equal(identity.identityRevealed,true);assert.equal(identity.trueVisualProfile,RefugeeIdentity.TrueProfiles[worldId]);}});
test('LifeBloom gates one compatible Elysia-born partner and survives Continue',()=>{const world=new World();world.create('human',212);const chosen=new CharacterCreator().createHuman({name:'Blu',sexCharacteristics:'female',genderIdentity:'woman',sexualOrientation:'bisexual'},world.findSpawnPosition(),212);world.addCharacter(chosen);world.hut=new Hut({id:'hut-1',position:world.findBuildPosition(chosen.position),storage:{wood:3,water:3,food:3}});world.homes=[world.hut];world.update(.1);assert.equal(world.householdProgression.state,'blooming');assert.equal(world.characters.length,1);assert.equal(world.effects.filter(e=>e.type==='lifeBloom').length,1);const restored=new World();restored.restore('human',212,null,world.toJSON());restored.update(3.6);const partner=restored.characters.find(c=>!c.chosenOne);assert.ok(partner);assert.equal(partner.originType,'elysiaBorn');assert.equal(partner.originWorldId,null);assert.equal(partner.isDisguised,false);assert.equal(CharacterCompatibility.isHumanCompatible(restored.characters.find(c=>c.chosenOne),partner),true);const continued=new World();continued.restore('human',212,null,restored.toJSON());continued.update(2);assert.equal(continued.characters.filter(c=>!c.chosenOne).length,1);continued.update(5);assert.equal(continued.householdProgression.chosenPartnerBloomCompleted,true);assert.equal(continued.households[0].memberIds.includes(partner.id),true);});
test('PartnerGenerator never assigns hidden Rival identity',()=>{const chosen=new Character({id:'c',name:'C',position:{x:1,y:1},worldType:'human',sexCharacteristics:'female',genderIdentity:'woman',sexualOrientation:'bisexual'});const partner=new PartnerGenerator().generate(chosen,{x:2,y:2},[chosen],1);assert.equal(partner.originType,'elysiaBorn');assert.equal(partner.trueSpecies,null);assert.equal(partner.originWorldId,null);});
