import { Config } from '../core/Config.js';
import { WorldTypeId } from '../data/WorldTypes.js';
import { CharacterCompatibility } from './CharacterCompatibility.js';
export class RelationshipSystem {
  constructor(world, data = {}) { this.world = world; this.elapsed = data.elapsed ?? 0; this.scores = { ...(data.scores ?? {}) }; this.initialize(); }
  key(firstId, secondId) { return [firstId, secondId].sort().join('::'); }
  score(firstId, secondId) { return this.scores[this.key(firstId, secondId)] ?? 0; }
  set(firstId, secondId, score) { if (firstId === secondId) return 0; return this.scores[this.key(firstId, secondId)] = Math.max(-100, Math.min(100, score)); }
  change(firstId, secondId, amount) { return this.set(firstId, secondId, this.score(firstId, secondId) + amount); }
  initialize() { for (const first of this.world.characters ?? []) for (const second of this.world.characters ?? []) { if (String(first.id)>=String(second.id) || this.scores[this.key(first.id,second.id)]!==undefined) continue; const partners=first.partnerId===second.id, family=RelationshipSystem.isCloseFamily(first,second), household=first.householdId&&first.householdId===second.householdId; this.set(first.id,second.id,partners?85:family?70:household?25:(first.settlementId&&first.settlementId===second.settlementId?8:0)); } }
  recordTheft(thiefId, victimIds, known = true) { if (!known) return false; for (const victimId of victimIds) this.change(thiefId,victimId,-28); return true; }
  recordHelp(helperId, recipientId) { return this.change(helperId,recipientId,14); }
  static isCloseFamily(first, second) { if (first.parentIds?.includes(second.id) || second.parentIds?.includes(first.id)) return true; return first.parentIds?.some(id => second.parentIds?.includes(id)) ?? false; }
  compatible(first, second) { if (!first.alive || !second.alive || first.lifeStage !== 'adult' || second.lifeStage !== 'adult' || first.partnerId || second.partnerId || RelationshipSystem.isCloseFamily(first, second)) return false; return this.world.worldType === WorldTypeId.BEAST ? CharacterCompatibility.isBeastCompatible(first, second) : CharacterCompatibility.isHumanCompatible(first, second); }
  update(deltaTime) { this.elapsed += deltaTime; if (this.elapsed < Config.SOCIAL_OPPORTUNITY_SECONDS) return; this.elapsed = 0; const singles = this.world.characters.filter(character => character.householdId && character.lifeStage === 'adult' && !character.partnerId); for (const first of singles) { const second = singles.find(candidate => candidate.id !== first.id && this.compatible(first, candidate)); if (second) { this.formCouple(first, second); return; } } }
  formCouple(first, second) { if (!this.compatible(first, second)) return false; first.partnerId = second.id; second.partnerId = first.id; this.set(first.id, second.id, 85); const homes = [this.world.findHome(first.homeBuildingId), this.world.findHome(second.homeBuildingId)].filter(Boolean).sort((a,b) => String(a.id).localeCompare(String(b.id))); const target = homes.find(home => home.householdId && this.world.households.find(h => h.id === home.householdId)?.memberIds.length === 1) ?? homes[0]; if (target) this.world.moveCharacterToHousehold(target.householdId, target.id, target.settlementId, target.id === first.homeBuildingId ? second : first); for (const home of homes) { const household = this.world.households.find(h => h.id === home.householdId); home.occupancy = household?.memberIds.length ? 'occupied' : 'vacant'; } this.world.reproduction.beginRelationship(first, second); this.world.addEffect(first.position, 'social'); return true; }
  toJSON() { return { elapsed: this.elapsed, scores: { ...this.scores } }; }
}
