import { Config } from '../core/Config.js';
import { WorldTypeId } from '../data/WorldTypes.js';
import { CharacterCompatibility } from './CharacterCompatibility.js';
export class RelationshipSystem {
  constructor(world, data = {}) { this.world = world; this.elapsed = data.elapsed ?? 0; }
  static isCloseFamily(first, second) { if (first.parentIds?.includes(second.id) || second.parentIds?.includes(first.id)) return true; return first.parentIds?.some(id => second.parentIds?.includes(id)) ?? false; }
  compatible(first, second) { if (!first.alive || !second.alive || first.lifeStage !== 'adult' || second.lifeStage !== 'adult' || first.partnerId || second.partnerId || RelationshipSystem.isCloseFamily(first, second)) return false; return this.world.worldType === WorldTypeId.BEAST ? CharacterCompatibility.isBeastCompatible(first, second) : CharacterCompatibility.isHumanCompatible(first, second); }
  update(deltaTime) { this.elapsed += deltaTime; if (this.elapsed < Config.SOCIAL_OPPORTUNITY_SECONDS) return; this.elapsed = 0; const singles = this.world.characters.filter(character => character.householdId && character.lifeStage === 'adult' && !character.partnerId); for (const first of singles) { const second = singles.find(candidate => candidate.id !== first.id && this.compatible(first, candidate)); if (second) { this.formCouple(first, second); return; } } }
  formCouple(first, second) { if (!this.compatible(first, second)) return false; first.partnerId = second.id; second.partnerId = first.id; const homes = [this.world.findHome(first.homeBuildingId), this.world.findHome(second.homeBuildingId)].filter(Boolean).sort((a,b) => String(a.id).localeCompare(String(b.id))); const target = homes.find(home => home.householdId && this.world.households.find(h => h.id === home.householdId)?.memberIds.length === 1) ?? homes[0]; if (target) this.world.moveCharacterToHousehold(target.householdId, target.id, target.settlementId, target.id === first.homeBuildingId ? second : first); for (const home of homes) { const household = this.world.households.find(h => h.id === home.householdId); home.occupancy = household?.memberIds.length ? 'occupied' : 'vacant'; } this.world.addEffect(first.position, 'social'); return true; }
  toJSON() { return { elapsed: this.elapsed }; }
}
