import { Resources } from '../data/Resources.js';
import { Pathfinder } from '../world/Pathfinder.js';
import { CharacterMovement } from '../entities/CharacterMovement.js';

export class CharacterAI {
  static Tasks = Object.freeze({ IDLE: 'idle', RETURN_HOME: 'returnHome', RESTING: 'resting', MEAL_CALL: 'mealCall', EATING: 'eating', WAITING_NIGHT: 'waitingNight', CHILD_IDLE: 'childIdle', FIND_TREE: 'findTree', MOVE_TREE: 'moveToTree', HARVEST: 'harvestTree', RETURN_WOOD: 'returnWood', BUILD: 'buildHut', FIND_WATER: 'findWater', MOVE_WATER: 'moveToWater', COLLECT_WATER: 'collectWater', RETURN_WATER: 'returnWater', FIND_COW: 'findCow', MOVE_COW: 'moveToCow', HUNT: 'huntCow', RETURN_FOOD: 'returnFood' });
  constructor(character, world) { this.character = character; this.world = world; this.pathfinder = new Pathfinder(); this.movement = new CharacterMovement(character); this.task = CharacterAI.Tasks.IDLE; this.targetId = null; this.actionTime = 0; this.carried = { wood: 0, water: 0, food: 0 }; }
  setTask(task) { this.task = task; this.character.aiTask = task; if (task === CharacterAI.Tasks.IDLE) { this.world.reservations.releaseFor(this.character.id); this.targetId = null; } }
  status() { const labels = { idle: 'Sta riposando', mealCall: 'Chiama la famiglia a tavola', eating: 'Sta mangiando', waitingNight: 'Attende la notte', childIdle: 'Gioca vicino a casa', returnHome: 'Sta tornando a casa', resting: 'Dorme in casa', findTree: 'Sta cercando legna', moveToTree: 'Sta andando verso un albero', harvestTree: 'Sta raccogliendo legna', buildHut: 'Sta costruendo una dimora', findWater: 'Sta cercando acqua', moveToWater: 'Sta andando verso una sorgente', findCow: 'Sta cercando cibo', moveToCow: 'Sta andando a caccia' }; return labels[this.task] ?? 'Sta tornando alla dimora'; }
  update(deltaTime) {
    if (this.character.insideHome || this.task === CharacterAI.Tasks.RESTING) return;
    if (this.character.lifeStage === 'child') { this.setTask(CharacterAI.Tasks.CHILD_IDLE); this.character.visualState = 'idle'; return; }
    if (this.task === CharacterAI.Tasks.RETURN_HOME) { if (this.movement.update(deltaTime)) { this.character.insideHome = true; this.character.visualState = 'sleep'; this.setTask(CharacterAI.Tasks.RESTING); } return; }
    if (this.task === CharacterAI.Tasks.IDLE) return this.choose();
    if ([CharacterAI.Tasks.MOVE_TREE, CharacterAI.Tasks.MOVE_WATER, CharacterAI.Tasks.MOVE_COW, CharacterAI.Tasks.RETURN_WOOD, CharacterAI.Tasks.RETURN_WATER, CharacterAI.Tasks.RETURN_FOOD].includes(this.task)) { if (this.movement.update(deltaTime)) this.arrive(); return; }
    if ([CharacterAI.Tasks.HARVEST, CharacterAI.Tasks.COLLECT_WATER, CharacterAI.Tasks.HUNT, CharacterAI.Tasks.BUILD].includes(this.task)) { this.actionTime -= deltaTime; this.character.visualState = this.task === CharacterAI.Tasks.BUILD ? 'work' : 'work'; if (this.actionTime <= 0) this.completeAction(); }
  }
  returnHome() { if (!this.world.hut || !this.character.householdId || this.character.insideHome) return false; this.world.reservations.releaseFor(this.character.id); this.targetId = null; this.movement.follow(this.pathfinder.findPath(this.world.terrain, this.character.position, this.world.hut.position)); this.character.visualState = 'walk'; this.setTask(CharacterAI.Tasks.RETURN_HOME); return true; }
  wake() { if (!this.character.insideHome && this.task !== CharacterAI.Tasks.RESTING) return; this.character.insideHome = false; this.character.position = { x: this.world.hut.position.x + (this.character.lifeStage === 'child' ? .7 : 1), y: this.world.hut.position.y + .5 }; this.character.visualState = 'idle'; this.setTask(this.character.lifeStage === 'child' ? CharacterAI.Tasks.CHILD_IDLE : CharacterAI.Tasks.IDLE); }
  choose() {
    if (!this.character.alive) { this.world.reservations.releaseFor(this.character.id); return; }
    if (!this.world.hut) { if (this.carried.wood >= 3) { const site = this.world.findBuildPosition(this.character.position); if (site) { this.world.beginHut(site); this.actionTime = 1.4; this.setTask(CharacterAI.Tasks.BUILD); } return; } this.seek(this.available(this.world.trees, tree => tree.harvestable), CharacterAI.Tasks.FIND_TREE, CharacterAI.Tasks.MOVE_TREE); return; }
    const options = Resources.ALL.filter(resource => !this.world.hut.storage.isFull(resource)).sort((a, b) => this.world.hut.storage.get(a) - this.world.hut.storage.get(b));
    for (const resource of options) { const collection = resource === Resources.WOOD ? this.world.trees : resource === Resources.WATER ? this.world.waterSources : this.world.cows; const target = this.available(collection, item => resource === Resources.WOOD ? item.harvestable : item.alive); if (target) { const find = resource === Resources.WOOD ? CharacterAI.Tasks.FIND_TREE : resource === Resources.WATER ? CharacterAI.Tasks.FIND_WATER : CharacterAI.Tasks.FIND_COW; const move = resource === Resources.WOOD ? CharacterAI.Tasks.MOVE_TREE : resource === Resources.WATER ? CharacterAI.Tasks.MOVE_WATER : CharacterAI.Tasks.MOVE_COW; this.seek(target, find, move); return; } }
    this.setTask(CharacterAI.Tasks.IDLE);
  }
  available(collection, predicate) { return collection.find(item => predicate(item) && !this.world.reservations.isReservedByOther(item.id, this.character.id)); }
  seek(target, findTask, moveTask) { this.setTask(findTask); if (!target || !this.world.reservations.reserve(target.id, this.character.id)) { this.setTask(CharacterAI.Tasks.IDLE); return; } const path = this.pathfinder.findPath(this.world.terrain, this.character.position, target.position); if (!path.length && Math.hypot(target.position.x - this.character.position.x, target.position.y - this.character.position.y) > 1) { this.setTask(CharacterAI.Tasks.IDLE); return; } this.targetId = target.id; this.movement.follow(path); this.setTask(moveTask); }
  arrive() { if (this.task.startsWith('return')) { const resource = this.task === CharacterAI.Tasks.RETURN_WOOD ? Resources.WOOD : this.task === CharacterAI.Tasks.RETURN_WATER ? Resources.WATER : Resources.FOOD; this.world.hut.storage.add(resource, this.carried[resource]); this.carried[resource] = 0; this.setTask(CharacterAI.Tasks.IDLE); return; } this.actionTime = 0.75; this.setTask(this.task === CharacterAI.Tasks.MOVE_TREE ? CharacterAI.Tasks.HARVEST : this.task === CharacterAI.Tasks.MOVE_WATER ? CharacterAI.Tasks.COLLECT_WATER : CharacterAI.Tasks.HUNT); }
  completeAction() { if (this.task === CharacterAI.Tasks.BUILD) { this.world.completeHut(); this.carried.wood -= 3; this.setTask(CharacterAI.Tasks.IDLE); return; } const entity = this.world.findEntity(this.targetId); if (!entity) { this.setTask(CharacterAI.Tasks.IDLE); return; } const resource = this.task === CharacterAI.Tasks.HARVEST ? Resources.WOOD : this.task === CharacterAI.Tasks.COLLECT_WATER ? Resources.WATER : Resources.FOOD; this.carried[resource] += resource === Resources.WOOD ? entity.harvest() : resource === Resources.WATER ? entity.collect() : entity.hunt(); this.world.reservations.releaseTarget(entity.id); this.world.addEffect(entity.position, 'valid'); if (!this.world.hut) this.setTask(CharacterAI.Tasks.IDLE); else { this.movement.follow(this.pathfinder.findPath(this.world.terrain, this.character.position, this.world.hut.position)); this.setTask(resource === Resources.WOOD ? CharacterAI.Tasks.RETURN_WOOD : resource === Resources.WATER ? CharacterAI.Tasks.RETURN_WATER : CharacterAI.Tasks.RETURN_FOOD); } }
  toJSON() { return { task: this.task, carried: { ...this.carried } }; }
  restore(data = {}) { this.world.reservations.releaseFor(this.character.id); this.carried = { ...this.carried, ...data.carried }; this.setTask(CharacterAI.Tasks.IDLE); }
}
