import { Resources } from '../data/Resources.js';
import { Pathfinder } from '../world/Pathfinder.js';
import { CharacterMovement } from '../entities/CharacterMovement.js';

export class CharacterAI {
  static Tasks = Object.freeze({ IDLE: 'idle', FIND_TREE: 'findTree', MOVE_TREE: 'moveToTree', HARVEST: 'harvestTree', RETURN_WOOD: 'returnWood', BUILD: 'buildHut', FIND_WATER: 'findWater', MOVE_WATER: 'moveToWater', COLLECT_WATER: 'collectWater', RETURN_WATER: 'returnWater', FIND_COW: 'findCow', MOVE_COW: 'moveToCow', HUNT: 'huntCow', RETURN_FOOD: 'returnFood' });
  constructor(character, world) { this.character = character; this.world = world; this.pathfinder = new Pathfinder(); this.movement = new CharacterMovement(character); this.task = CharacterAI.Tasks.IDLE; this.targetId = null; this.actionTime = 0; this.carried = { wood: 0, water: 0, food: 0 }; }
  setTask(task) { this.task = task; this.character.aiTask = task; }
  status() { const labels = { idle: 'Sta riposando', findTree: 'Sta cercando legna', moveToTree: 'Sta andando verso un albero', harvestTree: 'Sta raccogliendo legna', buildHut: 'Sta costruendo una capanna', findWater: 'Sta cercando acqua', moveToWater: 'Sta andando verso una sorgente', findCow: 'Sta cercando cibo', moveToCow: 'Sta andando a caccia' }; return labels[this.task] ?? 'Sta tornando alla capanna'; }
  update(deltaTime) {
    if (this.task === CharacterAI.Tasks.IDLE) return this.choose();
    if ([CharacterAI.Tasks.MOVE_TREE, CharacterAI.Tasks.MOVE_WATER, CharacterAI.Tasks.MOVE_COW, CharacterAI.Tasks.RETURN_WOOD, CharacterAI.Tasks.RETURN_WATER, CharacterAI.Tasks.RETURN_FOOD].includes(this.task)) { if (this.movement.update(deltaTime)) this.arrive(); return; }
    if ([CharacterAI.Tasks.HARVEST, CharacterAI.Tasks.COLLECT_WATER, CharacterAI.Tasks.HUNT, CharacterAI.Tasks.BUILD].includes(this.task)) { this.actionTime -= deltaTime; this.character.visualState = this.task === CharacterAI.Tasks.BUILD ? 'work' : 'work'; if (this.actionTime <= 0) this.completeAction(); }
  }
  choose() {
    if (!this.world.hut) { if (this.carried.wood >= 3) { const site = this.world.findBuildPosition(this.character.position); if (site) { this.world.beginHut(site); this.actionTime = 1.4; this.setTask(CharacterAI.Tasks.BUILD); } return; } this.seek(this.world.trees.find(tree => tree.harvestable), CharacterAI.Tasks.FIND_TREE, CharacterAI.Tasks.MOVE_TREE); return; }
    const options = Resources.ALL.filter(resource => !this.world.hut.storage.isFull(resource)).sort((a, b) => this.world.hut.storage.get(a) - this.world.hut.storage.get(b));
    for (const resource of options) { const target = resource === Resources.WOOD ? this.world.trees.find(item => item.harvestable) : resource === Resources.WATER ? this.world.waterSources.find(item => item.alive) : this.world.cows.find(item => item.alive); if (target) { const find = resource === Resources.WOOD ? CharacterAI.Tasks.FIND_TREE : resource === Resources.WATER ? CharacterAI.Tasks.FIND_WATER : CharacterAI.Tasks.FIND_COW; const move = resource === Resources.WOOD ? CharacterAI.Tasks.MOVE_TREE : resource === Resources.WATER ? CharacterAI.Tasks.MOVE_WATER : CharacterAI.Tasks.MOVE_COW; this.seek(target, find, move); return; } }
    this.setTask(CharacterAI.Tasks.IDLE);
  }
  seek(target, findTask, moveTask) { this.setTask(findTask); if (!target) { this.setTask(CharacterAI.Tasks.IDLE); return; } const path = this.pathfinder.findPath(this.world.terrain, this.character.position, target.position); if (!path.length && Math.hypot(target.position.x - this.character.position.x, target.position.y - this.character.position.y) > 1) { this.setTask(CharacterAI.Tasks.IDLE); return; } this.targetId = target.id; this.movement.follow(path); this.setTask(moveTask); }
  arrive() { if (this.task.startsWith('return')) { const resource = this.task === CharacterAI.Tasks.RETURN_WOOD ? Resources.WOOD : this.task === CharacterAI.Tasks.RETURN_WATER ? Resources.WATER : Resources.FOOD; this.world.hut.storage.add(resource, this.carried[resource]); this.carried[resource] = 0; this.setTask(CharacterAI.Tasks.IDLE); return; } this.actionTime = 0.75; this.setTask(this.task === CharacterAI.Tasks.MOVE_TREE ? CharacterAI.Tasks.HARVEST : this.task === CharacterAI.Tasks.MOVE_WATER ? CharacterAI.Tasks.COLLECT_WATER : CharacterAI.Tasks.HUNT); }
  completeAction() { if (this.task === CharacterAI.Tasks.BUILD) { this.world.completeHut(); this.carried.wood -= 3; this.setTask(CharacterAI.Tasks.IDLE); return; } const entity = this.world.findEntity(this.targetId); if (!entity) { this.setTask(CharacterAI.Tasks.IDLE); return; } const resource = this.task === CharacterAI.Tasks.HARVEST ? Resources.WOOD : this.task === CharacterAI.Tasks.COLLECT_WATER ? Resources.WATER : Resources.FOOD; this.carried[resource] += resource === Resources.WOOD ? entity.harvest() : resource === Resources.WATER ? entity.collect() : entity.hunt(); this.world.addEffect(entity.position, 'valid'); if (!this.world.hut) this.setTask(CharacterAI.Tasks.IDLE); else { this.movement.follow(this.pathfinder.findPath(this.world.terrain, this.character.position, this.world.hut.position)); this.setTask(resource === Resources.WOOD ? CharacterAI.Tasks.RETURN_WOOD : resource === Resources.WATER ? CharacterAI.Tasks.RETURN_WATER : CharacterAI.Tasks.RETURN_FOOD); } }
  toJSON() { return { task: this.task, carried: { ...this.carried } }; }
  restore(data = {}) { this.carried = { ...this.carried, ...data.carried }; this.setTask(CharacterAI.Tasks.IDLE); }
}
