import { RivalWorlds } from '../data/RivalWorlds.js';
import { EnemyTypes } from '../data/EnemyTypes.js';
import { Enemy } from '../entities/Enemy.js';
import { RefugeeIdentity } from '../entities/RefugeeIdentity.js';

export class InvasionSystem {
  static Introductions=Object.freeze({rivalWorld1:['Aurek Vael','« Sei sopravvissuto alla pietra che ho scagliato. Vediamo se le tue creature sopravvivono alle mie. »'],rivalWorld2:['Serath Vey','« Ho osservato ciò che hai costruito. Mi aspettavo di più. »'],rivalWorld3:['Quillix','« Oh. È davvero verde. Mi chiedevo cosa sarebbe successo inviando questi. »']});
  constructor(world,data={}){this.world=world;this.enemies=(data.enemies??[]).map(e=>new Enemy(e));this.active=data.active??false;this.currentRivalWorldId=data.currentRivalWorldId??null;this.targetSettlementId=data.targetSettlementId??null;this.revealedWorldIds=[...(data.revealedWorldIds??[])];this.revealedOmnipotentIds=[...(data.revealedOmnipotentIds??[])];this.introductionFlags={...(data.introductionFlags??{})};this.lastRivalWorldId=data.lastRivalWorldId??null;this.invasionCount=data.invasionCount??0;this.nextInvasionIn=data.nextInvasionIn??12;this.presentationRemaining=data.presentationRemaining??0;this.portalPosition=data.portalPosition?{...data.portalPosition}:null;}
  get introduction(){return this.presentationRemaining>0?InvasionSystem.Introductions[this.currentRivalWorldId]:null;}
  update(dt){if(this.presentationRemaining>0)this.presentationRemaining=Math.max(0,this.presentationRemaining-dt);if(this.active){this.world.combat.updateDefenders(dt);for(const enemy of this.enemies.filter(e=>e.alive))this.world.combat.updateEnemy(enemy,dt);if(!this.enemies.some(e=>e.alive)){this.active=false;this.lastRivalWorldId=this.currentRivalWorldId;this.currentRivalWorldId=null;this.nextInvasionIn=20;}return;}if(!this.world.rivalAttack.firstRivalAttackCompleted||!this.world.settlements.length)return;this.nextInvasionIn-=dt;if(this.nextInvasionIn<=0)this.start();}
  chooseWorld(){if(this.invasionCount===0)return'rivalWorld1';const unrevealed=RivalWorlds.all().map(w=>w.id).filter(id=>!this.revealedWorldIds.includes(id));if(unrevealed.length)return unrevealed[0];const options=RivalWorlds.all().map(w=>w.id).filter(id=>id!==this.lastRivalWorldId);return options[Math.abs((this.world.worldSeed??1)+this.invasionCount)%options.length];}
  start(rivalWorldId=this.chooseWorld(),size=null){if(this.active||!RivalWorlds.get(rivalWorldId))return false;const settlement=this.world.settlements.find(s=>this.world.characters.some(c=>c.alive&&c.settlementId===s.id))??this.world.settlements[0];if(!settlement)return false;const position=this.world.findEdgeReachablePosition(settlement.center);if(!position)return false;const firstArrival=!this.revealedWorldIds.includes(rivalWorldId);const type=EnemyTypes.forWorld(rivalWorldId);this.active=true;this.currentRivalWorldId=rivalWorldId;this.targetSettlementId=settlement.id;this.portalPosition={...position};this.invasionCount+=1;const count=size??(this.invasionCount<=3?2:2+Math.abs((this.world.worldSeed??0)+this.invasionCount)%3);this.enemies=[];for(let i=0;i<count;i+=1)this.enemies.push(new Enemy({id:`enemy-${this.invasionCount}-${i+1}`,typeId:type.id,position:{x:position.x+(i%2)*.65,y:position.y+Math.floor(i/2)*.65},visualVariant:i%3}));if(firstArrival){this.revealRefugees(rivalWorldId);this.revealedWorldIds.push(rivalWorldId);this.revealedOmnipotentIds.push(rivalWorldId);this.introductionFlags[rivalWorldId]=true;this.presentationRemaining=5;}this.world.addEffect(position,'rivalPortal',{rivalWorldId,duration:3});return true;}
  revealRefugees(rivalWorldId){const matches=this.world.characters.filter(character=>character.alive&&character.isDisguised&&character.originWorldId===rivalWorldId&&character.originType==='externalMigrant');if(!matches.length)return null;const witness=matches[0];this.world.ais.get(witness.id)?.interrupt();witness.aiTask='witnessingInvasion';RefugeeIdentity.reveal(witness,true);this.rememberReveal(witness,rivalWorldId);witness.speechLines=['No... loro no.',RefugeeIdentity.historyLine(witness)];witness.speechRemaining=8;this.world.addEffect(witness.position,'identityReveal',{duration:2.8,characterId:witness.id,dramatic:true});for(const character of matches.slice(1)){RefugeeIdentity.reveal(character);this.rememberReveal(character,rivalWorldId);this.world.addEffect(character.position,'identityReveal',{duration:2,characterId:character.id});}return witness;}
  lightningAt(position){const enemy=this.enemies.find(e=>e.alive&&Math.hypot(e.position.x-position.x,e.position.y-position.y)<=1.25);if(!enemy)return null;enemy.takeDamage(enemy.health);this.world.addEffect(enemy.position,'lightning',{enemyId:enemy.id});return enemy;}
  rememberReveal(character,rivalWorldId){character.memories?.remember({eventType:'TRUE_FORM_REVEAL',participants:[character.id],resource:rivalWorldId,cycle:this.world.worldTime?.cycle??0,emotionalImpact:-.7,importance:1,knowledgeSource:'WITNESSED'});character.knowledge?.learn({type:'trueForm',subjectId:character.id,objectId:rivalWorldId,source:'WITNESSED',certainty:1,cycle:this.world.worldTime?.cycle??0});}
  toJSON(){return{enemies:this.enemies.filter(e=>e.alive).map(e=>e.toJSON()),active:this.active,currentRivalWorldId:this.currentRivalWorldId,targetSettlementId:this.targetSettlementId,revealedWorldIds:[...this.revealedWorldIds],revealedOmnipotentIds:[...this.revealedOmnipotentIds],introductionFlags:{...this.introductionFlags},lastRivalWorldId:this.lastRivalWorldId,invasionCount:this.invasionCount,nextInvasionIn:this.nextInvasionIn,presentationRemaining:this.presentationRemaining,portalPosition:this.portalPosition?{...this.portalPosition}:null};}
}
