import { Config } from '../core/Config.js';

export class WorldEventConfig {
  static FIRST_CYCLE = 3;
  static MIN_CYCLE_GAP = 2;
  static MAX_CYCLE_GAP = 4;
  static REPEAT_COOLDOWN_CYCLES = 5;
  static MAX_MAJOR_ACTIVE = 1;
  static MAX_MINOR_ACTIVE = 2;
  static HISTORY_LIMIT = 24;
  static DURATIONS = Object.freeze({ DRY_WATER_SOURCE: 55, TREE_FIRE: 28, SICK_FOOD_SOURCE: 48, LOST_CHILD: 75, RESOURCE_DISPUTE: 12, WORK_INJURY: 42, FAMILY_ARGUMENT: 10, NEWCOMER_NEEDS_HELP: 45, INVASION_AFTERMATH: 35 });
  static SEVERITY = Object.freeze({ DRY_WATER_SOURCE: 'MAJOR', TREE_FIRE: 'MAJOR', SICK_FOOD_SOURCE: 'MODERATE', LOST_CHILD: 'MAJOR', RESOURCE_DISPUTE: 'MODERATE', WORK_INJURY: 'MODERATE', FAMILY_ARGUMENT: 'MINOR', NEWCOMER_NEEDS_HELP: 'MODERATE', INVASION_AFTERMATH: 'MODERATE' });
  static FIRE_SPREAD_CHANCE = .22;
  static FIRE_SPREAD_RADIUS = 4;
  static FIRE_MAX_TREES = 4;
  static FIRE_SPREAD_INTERVAL = 6;
  static INJURY_SPEED_FACTOR = .52;
  static INJURY_REST_SECONDS = 24;
  static seconds(type) { return this.DURATIONS[type] ?? Config.WORLD_CYCLE_SECONDS; }
}
