import { WorldEvent } from './WorldEvent.js';
import { WorldEventConfig } from './WorldEventConfig.js';
import { WorldTypeId } from '../data/WorldTypes.js';
import { CommunicationIntent } from '../dialogue/CommunicationIntent.js';
import { Pathfinder } from '../world/Pathfinder.js';

export class WorldEventSystem {
  static Types = Object.freeze({ DRY_WATER_SOURCE: 'DRY_WATER_SOURCE', TREE_FIRE: 'TREE_FIRE', SICK_FOOD_SOURCE: 'SICK_FOOD_SOURCE', LOST_CHILD: 'LOST_CHILD', RESOURCE_DISPUTE: 'RESOURCE_DISPUTE', WORK_INJURY: 'WORK_INJURY', FAMILY_ARGUMENT: 'FAMILY_ARGUMENT', NEWCOMER_NEEDS_HELP: 'NEWCOMER_NEEDS_HELP', INVASION_AFTERMATH: 'INVASION_AFTERMATH' });
  constructor(world, data = {}) { this.world = world; this.activeEvents = (data.activeEvents ?? data.active ?? []).map(item => new WorldEvent(item)); this.history = [...(data.history ?? [])].slice(-WorldEventConfig.HISTORY_LIMIT); this.recentTypes = { ...(data.recentTypes ?? {}) }; this.nextId = data.nextId ?? 1; this.nextCycle = data.nextCycle ?? WorldEventConfig.FIRST_CYCLE; this.lastScheduledSettlementIndex = data.lastScheduledSettlementIndex ?? -1; this.restoreEffects(); }
  get active() { return this.activeEvents; }
  isEligible(type, settlement = null) { if (this.world.worldType === WorldTypeId.PLANT) return false; const residents = this.residents(settlement); const homes = new Set(residents.map(c => c.householdId).filter(Boolean)); if (type === WorldEventSystem.Types.DRY_WATER_SOURCE) return this.world.waterSources.some(s => s.alive && !s.dry);
    if (type === WorldEventSystem.Types.TREE_FIRE) return this.world.trees.some(t => t.alive && t.harvestable && !t.burning);
    if (type === WorldEventSystem.Types.SICK_FOOD_SOURCE) return (this.world.worldType === WorldTypeId.BEAST ? this.world.animalFoodSources : this.world.cows).some(s => s.alive && !s.sick && !s.spoiled);
    if (type === WorldEventSystem.Types.LOST_CHILD) return residents.some(c => c.alive && c.lifeStage === 'child' && !c.lost && c.parentIds.some(id => residents.some(p => p.id === id && p.alive)));
    if (type === WorldEventSystem.Types.RESOURCE_DISPUTE) return homes.size >= 2 && this.isScarce(settlement);
    if (type === WorldEventSystem.Types.WORK_INJURY) return residents.some(c => c.alive && c.lifeStage === 'adult' && !c.injured && ['harvestTree','gatherFood','buildHut','moveToTree','moveToFood'].includes(this.world.ais.get(c.id)?.task));
    if (type === WorldEventSystem.Types.FAMILY_ARGUMENT) return residents.some(c => c.alive && c.partnerId && residents.some(p => p.id === c.partnerId && p.alive) && (c.needs.happiness < .55 || c.needs.safety < .5));
    if (type === WorldEventSystem.Types.NEWCOMER_NEEDS_HELP) return Boolean(settlement?.isGrowing?.() && residents.some(c => c.alive && c.newcomer && !c.migrantNeed && !c.householdId));
    return false; }
  residents(settlement) { return this.world.characters.filter(c => c.alive && (!settlement || c.settlementId === settlement.id)); }
  isScarce(settlement) { const homes = this.world.homes.filter(h => !settlement || h.settlementId === settlement.id || settlement.homeBuildingIds.includes(h.id)); return homes.length > 1 && homes.some(h => h.storage?.get('food') < 2); }
  eligibleTypes(settlement) { return Object.values(WorldEventSystem.Types).filter(type => type !== WorldEventSystem.Types.INVASION_AFTERMATH && this.isEligible(type, settlement) && (this.world.worldTime.cycle - (this.recentTypes[type] ?? -99)) >= WorldEventConfig.REPEAT_COOLDOWN_CYCLES); }
  canStart(type) { const major = WorldEventConfig.SEVERITY[type] === 'MAJOR'; return major ? this.activeEvents.filter(e => e.severity === 'MAJOR').length < WorldEventConfig.MAX_MAJOR_ACTIVE : this.activeEvents.filter(e => e.severity !== 'MAJOR').length < WorldEventConfig.MAX_MINOR_ACTIVE; }
  schedule(type, settlement = null, options = {}) { if (!this.isEligible(type, settlement) || !this.canStart(type)) { this.trace('eventSuppressed', { eventType: type }); return null; } const target = this.selectTarget(type, settlement); if (!target) return null; const event = new WorldEvent({ id: `world-event-${this.nextId++}`, type, settlementId: settlement?.id ?? target.settlementId ?? null, targetId: target.id, target: { id: target.id, kind: target.kind ?? (target.lifeStage ? 'character' : 'location'), position: { ...target.position } }, startCycle: this.world.worldTime.cycle, startTime: this.world.simulationTime, duration: options.duration ?? WorldEventConfig.seconds(type), remaining: options.duration ?? WorldEventConfig.seconds(type), severity: WorldEventConfig.SEVERITY[type], participants: options.participants ?? this.participants(type, target, settlement) }); this.activeEvents.push(event); this.trace('eventScheduled', { eventId: event.id, eventType: type }); this.start(event); return event; }
  start(event) { if (!event.activate()) return false; this.apply(event); this.recentTypes[event.type] = this.world.worldTime.cycle; this.trace('eventStarted', { eventId: event.id, eventType: event.type }); this.trace('eventTarget', { eventId: event.id, targetId: event.targetId, settlementId: event.settlementId }); return event; }
  selectTarget(type, settlement) { const residents = this.residents(settlement); if (type === 'DRY_WATER_SOURCE') return this.nearest(this.world.waterSources.filter(s => s.alive && !s.dry), settlement?.center); if (type === 'TREE_FIRE') return this.nearest(this.world.trees.filter(t => t.alive && t.harvestable && !t.burning), settlement?.center); if (type === 'SICK_FOOD_SOURCE') return this.nearest((this.world.worldType === WorldTypeId.BEAST ? this.world.animalFoodSources : this.world.cows).filter(s => s.alive && !s.sick && !s.spoiled), settlement?.center); if (type === 'LOST_CHILD') return residents.find(c => c.lifeStage === 'child' && !c.lost && c.parentIds.some(id => residents.some(p => p.id === id && p.alive))); if (type === 'WORK_INJURY') return residents.find(c => c.lifeStage === 'adult' && !c.injured && ['harvestTree','gatherFood','buildHut','moveToTree','moveToFood'].includes(this.world.ais.get(c.id)?.task)); if (type === 'FAMILY_ARGUMENT') return residents.find(c => c.partnerId && residents.some(p => p.id === c.partnerId) && (c.needs.happiness < .55 || c.needs.safety < .5)); if (type === 'NEWCOMER_NEEDS_HELP') return residents.find(c => c.newcomer && !c.householdId && !c.migrantNeed); if (type === 'RESOURCE_DISPUTE') return residents.find(c => c.householdId); return null; }
  nearest(items, point) { return !point ? items[0] : [...items].sort((a,b) => Math.hypot(a.position.x-point.x,a.position.y-point.y)-Math.hypot(b.position.x-point.x,b.position.y-point.y))[0]; }
  participants(type, target, settlement) { const residents=this.residents(settlement); if (type==='LOST_CHILD') return [...new Set([target.id,...target.parentIds.filter(id=>residents.some(c=>c.id===id))])]; if(type==='FAMILY_ARGUMENT')return [target.id,target.partnerId]; if(type==='RESOURCE_DISPUTE'){const other=residents.find(c=>c.householdId&&c.householdId!==target.householdId);return other?[target.id,other.id]:[];} return target.lifeStage?[target.id]:residents.filter(c=>Math.hypot(c.position.x-target.position.x,c.position.y-target.position.y)<7).slice(0,4).map(c=>c.id); }
  apply(event) { const target=this.world.findEntity(event.targetId)??this.world.characters.find(c=>c.id===event.targetId); if(!target)return; if(event.type==='DRY_WATER_SOURCE')target.dry=true; if(event.type==='TREE_FIRE'){target.burning=true;event.affectedTreeIds=[target.id];} if(event.type==='SICK_FOOD_SOURCE'){target.sick=this.world.worldType!==WorldTypeId.BEAST;target.spoiled=this.world.worldType===WorldTypeId.BEAST;} if(event.type==='WORK_INJURY'||event.type==='NEWCOMER_NEEDS_HELP'){target.injured=true;target.injuryRemaining=WorldEventConfig.INJURY_REST_SECONDS;target.migrantNeed=event.type==='NEWCOMER_NEEDS_HELP'?'injured':target.migrantNeed;target.needs?.danger(.2);this.world.ais.get(target.id)?.returnHome();} if(event.type==='LOST_CHILD')this.loseChild(event,target); if(event.type==='RESOURCE_DISPUTE')this.beginDispute(event); if(event.type==='FAMILY_ARGUMENT')this.beginArgument(event); this.inform(event); }
  loseChild(event, child) { const home=this.world.homeFor(child); const origin=home?.position??child.position; const candidates=[]; for(let y=Math.max(1,Math.floor(origin.y-9));y<Math.min(this.world.terrain.height-1,origin.y+10);y++)for(let x=Math.max(1,Math.floor(origin.x-9));x<Math.min(this.world.terrain.width-1,origin.x+10);x++)if(this.world.isWalkable(x,y)&&Math.hypot(x-origin.x,y-origin.y)>=6)candidates.push({x:x+.5,y:y+.5}); const destination=candidates.find(p=>new Pathfinder().findPath(this.world.terrain,child.position,p).length)??child.position; child.lost=true;child.insideHome=false;child.position={...destination};event.target.position={...destination}; for(const id of child.parentIds){const parent=this.world.characters.find(c=>c.id===id&&c.alive);if(parent){parent.knowledge.learn({type:'location',subjectId:child.id,location:'agli alberi',eventId:event.id,certainty:.55,source:'ASSUMED',cycle:this.world.worldTime.cycle}); this.world.ais.get(parent.id)?.rally(new Pathfinder().findPath(this.world.terrain,parent.position,destination));}}
  }
  inform(event) { for(const id of event.participants){const c=this.world.characters.find(x=>x.id===id&&x.alive);if(!c)continue;c.knowledge.learn({type:'worldEvent',subjectId:event.targetId,eventType:event.type,eventId:event.id,source:'WITNESSED',cycle:this.world.worldTime.cycle});} const speaker=this.world.characters.find(c=>c.id===event.participants[0]&&c.alive); if(speaker){this.world.dialogue.say(new CommunicationIntent({speakerId:speaker.id,targetType:'PLAYER',intent:'REQUEST_HELP',eventType:event.type,subjectId:event.targetId,priority:event.severity==='MAJOR'?'CRITICAL':'HIGH',emotion:'WORRIED'}));event.requestMade=true;} this.world.eventNotification={eventId:event.id,text:this.notification(event),position:{...event.target.position},remaining:8}; }
  notification(event){const settlement=this.world.settlements.find(s=>s.id===event.settlementId)?.name??'un insediamento';return event.type==='DRY_WATER_SOURCE'?`Qualcosa non va alla fonte di ${settlement}.`:event.type==='TREE_FIRE'?`Un albero sta bruciando vicino a ${settlement}.`:event.type==='LOST_CHILD'?`Una famiglia di ${settlement} cerca un bambino.`:`Gli abitanti di ${settlement} hanno bisogno di aiuto.`;}
  beginDispute(event){const [a,b]=event.participants.map(id=>this.world.characters.find(c=>c.id===id));if(!a||!b)return;const relation=this.world.relationships.score(a.id,b.id)/100;const kindness=(a.personality.kindness+b.personality.kindness)/2;event.proposedOutcome=relation+kindness>.8?'SHARE':a.personality.selfishness>.65?'STEAL_LATER':'ARGUE';this.world.dialogue.say(new CommunicationIntent({speakerId:a.id,targetType:'NEARBY_CHARACTER',targetId:b.id,intent:'REPORT_EVENT',eventType:event.type,textMeaning:'State prendendo tutto il cibo.',priority:'HIGH'}));}
  beginArgument(event){const [a,b]=event.participants.map(id=>this.world.characters.find(c=>c.id===id));if(!a||!b)return;event.proposedOutcome=(a.personality.kindness+b.personality.kindness)>.9?'RECONCILIATION':'CONTINUED_TENSION';this.world.dialogue.say(new CommunicationIntent({speakerId:a.id,targetType:'NEARBY_CHARACTER',targetId:b.id,intent:'REPORT_EVENT',eventType:event.type,textMeaning:'Dobbiamo parlarne, senza ferirci.',priority:'NORMAL'}));}
  update(deltaTime) { if(this.world.worldType===WorldTypeId.PLANT)return; if(this.world.eventNotification){this.world.eventNotification.remaining-=deltaTime;if(this.world.eventNotification.remaining<=0)this.world.eventNotification=null;} for(const event of [...this.activeEvents])this.updateEvent(event,deltaTime); if(this.world.worldTime.cycle>=this.nextCycle&&!this.activeEvents.some(e=>e.severity==='MAJOR'))this.scheduleNext(); }
  scheduleNext(){const settlements=this.world.settlements.length?this.world.settlements:[null];for(let offset=1;offset<=settlements.length;offset++){const index=(this.lastScheduledSettlementIndex+offset)%settlements.length,settlement=settlements[index],types=this.eligibleTypes(settlement);if(types.length){const hash=Math.abs((this.world.worldSeed??1)+this.world.worldTime.cycle+this.nextId);const event=this.schedule(types[hash%types.length],settlement);if(event){this.lastScheduledSettlementIndex=index;this.nextCycle=this.world.worldTime.cycle+WorldEventConfig.MIN_CYCLE_GAP+(hash%(WorldEventConfig.MAX_CYCLE_GAP-WorldEventConfig.MIN_CYCLE_GAP+1));return event;}}}this.nextCycle=this.world.worldTime.cycle+1;return null;}
  updateEvent(event,dt){if(event.status!=='ACTIVE')return;event.elapsed+=dt;event.remaining=Math.max(0,event.remaining-dt); if(event.type==='TREE_FIRE')this.updateFire(event,dt); if(event.type==='WORK_INJURY'||event.type==='NEWCOMER_NEEDS_HELP')this.updateInjury(event,dt); if(event.type==='LOST_CHILD'&&this.childHome(event))return this.resolve(event,this.world.rally?'RETURNED_BY_RALLY':'FOUND_BY_PARENT'); if(!event.absenceRemembered&&event.severity==='MAJOR'&&event.elapsed>event.duration*.55){event.absenceRemembered=true;for(const id of event.participants){const c=this.world.characters.find(x=>x.id===id);if(c){const memory=c.memories.remember({eventType:'major_abandonment',participants:[event.targetId],cycle:this.world.worldTime.cycle,importance:.7,emotionalImpact:c.personality.faithDisposition>.5?-.45:-.15,eventId:event.id});this.world.beliefSystem.observe(c,memory,{beliefType:'THE_OMNIPOTENT_HAS_ABANDONED_US',reasonKnown:true,faithImpact:-.04});}}} if(event.remaining<=0)this.naturalResolve(event);}
  updateFire(event,dt){event.spreadElapsed+=dt;if(event.spreadElapsed<WorldEventConfig.FIRE_SPREAD_INTERVAL||event.affectedTreeIds.length>=WorldEventConfig.FIRE_MAX_TREES)return;event.spreadElapsed=0;const burning=this.world.trees.filter(t=>event.affectedTreeIds.includes(t.id)&&t.alive);const candidates=this.world.trees.filter(t=>t.alive&&t.harvestable&&!t.burning&&burning.some(b=>Math.hypot(t.position.x-b.position.x,t.position.y-b.position.y)<=WorldEventConfig.FIRE_SPREAD_RADIUS));const roll=((event.startCycle*31+event.affectedTreeIds.length*17+this.world.worldSeed)%100)/100;if(candidates[0]&&roll<WorldEventConfig.FIRE_SPREAD_CHANCE){candidates[0].burning=true;event.affectedTreeIds.push(candidates[0].id);this.trace('eventEscalated',{eventId:event.id,targetId:candidates[0].id});}}
  updateInjury(event,dt){const c=this.world.characters.find(x=>x.id===event.targetId);if(!c?.injured)return this.resolve(event,'RECOVERED_NATURALLY');if(c.insideHome)c.injuryRemaining=Math.max(0,(c.injuryRemaining??WorldEventConfig.INJURY_REST_SECONDS)-dt);if(c.injuryRemaining<=0){c.injured=false;this.resolve(event,'RECOVERED_NATURALLY');}}
  childHome(event){const child=this.world.characters.find(c=>c.id===event.targetId);const home=child&&this.world.homeFor(child);return Boolean(child?.lost&&home&&Math.hypot(child.position.x-home.position.x,child.position.y-home.position.y)<2);}
  naturalResolve(event){const target=this.world.findEntity(event.targetId)??this.world.characters.find(c=>c.id===event.targetId);if(event.type==='DRY_WATER_SOURCE'){target.dry=false;return this.resolve(event,'RECOVERED_NATURALLY');}if(event.type==='TREE_FIRE'){for(const id of event.affectedTreeIds){const tree=this.world.findEntity(id);if(tree){tree.burning=false;tree.harvestable=false;tree.alive=false;}}return this.resolve(event,'BURNED_OUT');}if(event.type==='SICK_FOOD_SOURCE'){target.alive=false;target.sick=false;target.spoiled=false;return this.resolve(event,'SOURCE_EXPIRED');}if(event.type==='LOST_CHILD'){event.remaining=15;return;}if(event.type==='RESOURCE_DISPUTE')return this.resolve(event,event.proposedOutcome??'WITHDRAW');if(event.type==='FAMILY_ARGUMENT')return this.resolve(event,event.proposedOutcome??'TEMPORARY_ANGER');if(event.type==='WORK_INJURY'||event.type==='NEWCOMER_NEEDS_HELP'){target.injured=false;return this.resolve(event,'RECOVERED_NATURALLY');}return this.resolve(event,'EXPIRED',WorldEvent.Status.EXPIRED);}
  intervene(powerId,position,targetCharacter=null){const hits=this.activeEvents.filter(e=>Math.hypot(e.target.position.x-position.x,e.target.position.y-position.y)<=3||e.participants.includes(targetCharacter?.id));for(const event of hits){if(powerId==='water'&&event.type==='DRY_WATER_SOURCE'){this.world.findEntity(event.targetId).dry=false;this.resolve(event,'RESTORED_BY_DIVINE_WATER',undefined,powerId);}else if(powerId==='water'&&event.type==='TREE_FIRE'){for(const id of event.affectedTreeIds){const t=this.world.findEntity(id);if(t)t.burning=false;}this.resolve(event,'EXTINGUISHED_BY_DIVINE_WATER',undefined,powerId);}else if(powerId==='blessing'&&['WORK_INJURY','NEWCOMER_NEEDS_HELP'].includes(event.type)&&event.targetId===targetCharacter?.id){targetCharacter.injured=false;targetCharacter.injuryRemaining=0;this.resolve(event,'BLESSED_HEALED',undefined,powerId);}else if(powerId==='blessing'&&event.type==='SICK_FOOD_SOURCE'){const source=this.world.findEntity(event.targetId);source.sick=false;source.spoiled=false;this.resolve(event,'PURIFIED_BY_BLESSING',undefined,powerId);}else if(powerId==='rayOfLight'&&event.type==='LOST_CHILD'){const child=this.world.characters.find(c=>c.id===event.targetId),home=this.world.homeFor(child);if(Math.hypot(position.x-child.position.x,position.y-child.position.y)<4||Math.hypot(position.x-home.position.x,position.y-home.position.y)<4){child.position={...home.position};child.lost=false;this.resolve(event,'RETURNED_BY_RALLY',undefined,powerId);}}else if(powerId==='lightning'&&['RESOURCE_DISPUTE','FAMILY_ARGUMENT'].includes(event.type))this.resolve(event,'WITHDREW_AFTER_DIVINE_WARNING',undefined,powerId);}}
  resolve(event,outcome,status=WorldEvent.Status.RESOLVED,divine=null){if(!event.finish(outcome,status))return false;event.divineIntervention=divine;const child=event.type==='LOST_CHILD'&&this.world.characters.find(c=>c.id===event.targetId);if(child)child.lost=false;for(const id of event.participants){const c=this.world.characters.find(x=>x.id===id);if(!c)continue;c.knowledge.learn({type:'worldEventOutcome',subjectId:event.targetId,eventType:event.type,outcome,eventId:event.id,source:'WITNESSED',cycle:this.world.worldTime.cycle});const memory=c.memories.remember({eventType:event.type+(divine?'_RESOLVED':''),participants:event.participants,cycle:this.world.worldTime.cycle,outcome,divineIntervention:divine,importance:event.severity==='MAJOR'?1:.65,emotionalImpact:divine?.5:0,resolved:true});if(divine){const beliefType=event.type==='DRY_WATER_SOURCE'?'THE_OMNIPOTENT_PROVIDES_WHEN_WE_SUFFER':event.type==='LOST_CHILD'?'THE_OMNIPOTENT_PROTECTS_CHILDREN':['WORK_INJURY','NEWCOMER_NEEDS_HELP'].includes(event.type)?'THE_OMNIPOTENT_FAVORS_SOME_PEOPLE':null;if(beliefType)this.world.beliefSystem.observe(c,memory,{beliefType,reasonKnown:true,inCrisis:true});}this.trace('eventMemoryCreated',{eventId:event.id,characterId:c.id});}this.history.push({id:event.id,type:event.type,settlementId:event.settlementId,cycle:this.world.worldTime.cycle,outcome,participants:[...event.participants],divineIntervention:divine});this.history=this.history.slice(-WorldEventConfig.HISTORY_LIMIT);this.activeEvents=this.activeEvents.filter(e=>e.id!==event.id);this.trace(divine?'eventDivineIntervention':'eventNaturalResolution',{eventId:event.id,outcome,powerId:divine});this.trace('eventResolved',{eventId:event.id,outcome});return true;}
  restoreEffects(){for(const event of this.activeEvents.filter(e=>e.status==='ACTIVE')){const target=this.world.findEntity(event.targetId)??this.world.characters.find(c=>c.id===event.targetId);if(!target)continue;if(event.type==='DRY_WATER_SOURCE')target.dry=true;if(event.type==='TREE_FIRE')for(const id of event.affectedTreeIds){const t=this.world.findEntity(id);if(t)t.burning=true;}if(event.type==='SICK_FOOD_SOURCE'){target.sick=this.world.worldType!==WorldTypeId.BEAST;target.spoiled=this.world.worldType===WorldTypeId.BEAST;}if(['WORK_INJURY','NEWCOMER_NEEDS_HELP'].includes(event.type))target.injured=true;if(event.type==='LOST_CHILD')target.lost=true;}}
  trace(type,data={}){this.world.diagnostics?.trace(type,data);}
  toJSON(){return{activeEvents:this.activeEvents.map(e=>e.toJSON()),history:this.history.map(e=>({...e,participants:[...e.participants]})),recentTypes:{...this.recentTypes},nextId:this.nextId,nextCycle:this.nextCycle,lastScheduledSettlementIndex:this.lastScheduledSettlementIndex};}
}
