export class Config {
  static VERSION = 'Alpha 0.0.8';
  static MAX_DELTA_SECONDS = 0.1;
  static BACKGROUND_COLOR = '#25282a';
  static SAVE_KEY = 'elysia_reboot_save_v1';
  static SAVE_VERSION = 1;
  static DAY_DURATION_SECONDS = 240;
  static NIGHT_DURATION_SECONDS = 60;
  static WORLD_CYCLE_SECONDS = Config.DAY_DURATION_SECONDS + Config.NIGHT_DURATION_SECONDS;
  static DAWN_DURATION_SECONDS = 15;
  static DUSK_DURATION_SECONDS = 15;
  static INTIMACY_PROBABILITY = 0.35;
  static NEW_LIFE_PROBABILITY_AFTER_INTIMACY = 0.35;
  static MEAL_INTERVAL_SECONDS = 60;
  static MEAL_ANNOUNCEMENT_SECONDS = 2.25;
  static MEAL_DURATION_SECONDS = 3;
  static NEW_LIFE_MESSAGE_SECONDS = 6;
  static ANIMAL_FOOD_YIELD = 3;
  static NEW_HOME_WOOD_COST = 3;
  static CENTRAL_STORAGE_CAPACITY = 30;
  static SETTLEMENT_HOME_MILESTONE = 4;
  static POPULATION_LIMIT = 24;
  static SOCIAL_OPPORTUNITY_SECONDS = 20;
}
