import { Pathfinder } from '../world/Pathfinder.js';
import { CommunicationIntent } from '../dialogue/CommunicationIntent.js';
import { SettlementRelationship } from './SettlementRelationship.js';
import { SettlementVisit } from './SettlementVisit.js';
import { AidDelivery } from './AidDelivery.js';

export class SettlementDiplomacySystem {
  static RESOURCES=Object.freeze(['food','water','wood']);
  constructor(world,data={}){this.world=world;this.relationships=(data.relationships??[]).map(item=>new SettlementRelationship(item));this.visits=(data.visits??[]).map(item=>new SettlementVisit(item));this.deliveries=(data.deliveries??[]).map(item=>new AidDelivery(item));this.requests=(data.requests??[]).map(item=>({...item}));this.nextId=data.nextId??1;this.lastVisitCycle={...(data.lastVisitCycle??{})};this.accumulator=0;this.ensureRelations();this.restoreCharacterVisitState();}
  key(a,b){return[a,b].sort().join('|');}
  relation(a,b){return this.relationships.find(item=>this.key(item.settlementAId,item.settlementBId)===this.key(a,b))??null;}
  view(observerId,otherId){return this.relation(observerId,otherId)?.perception(observerId)??null;}
  ensureRelations(){const active=new Set(this.world.settlements.map(s=>s.id));this.relationships=this.relationships.filter(r=>active.has(r.settlementAId)&&active.has(r.settlementBId));for(let a=0;a<this.world.settlements.length;a++)for(let b=a+1;b<this.world.settlements.length;b++)if(!this.relation(this.world.settlements[a].id,this.world.settlements[b].id)){const relation=new SettlementRelationship({settlementAId:this.world.settlements[a].id,settlementBId:this.world.settlements[b].id});this.seedFamilyAffinity(relation);this.relationships.push(relation);this.trace('settlementRelationCreated',{settlementAId:relation.settlementAId,settlementBId:relation.settlementBId});}}
  seedFamilyAffinity(relation){const a=this.world.settlements.find(s=>s.id===relation.settlementAId),b=this.world.settlements.find(s=>s.id===relation.settlementBId),fa=this.world.characters.find(c=>c.id===a?.founderId),fb=this.world.characters.find(c=>c.id===b?.founderId);if(fa&&fb&&(fa.parentIds?.includes(fb.id)||fb.parentIds?.includes(fa.id)||fa.parentIds?.some(id=>fb.parentIds?.includes(id)))){relation.change(a.id,{affinity:12,trust:5});relation.change(b.id,{affinity:12,trust:5});}}
  trace(type,details){return this.world.diagnostics?.trace(type,details);}
  settlementStorage(id){const settlement=this.world.settlements.find(s=>s.id===id),homes=this.world.homes.filter(h=>h.settlementId===id&&h.storage);const central=this.world.findHome?.(settlement?.centralStructureId??settlement?.foundingHomeId);return central?.storage??homes[0]?.storage??null;}
  shortage(settlementId){const storage=this.settlementStorage(settlementId);if(!storage)return null;return SettlementDiplomacySystem.RESOURCES.map(resource=>({resource,amount:storage.get(resource)})).filter(item=>item.amount<=1).sort((a,b)=>a.amount-b.amount)[0]??null;}
  requestAid(requesterId,targetId,resource=null){const need=this.shortage(requesterId);if(!need||resource&&need.resource!==resource)return null;if(this.requests.some(r=>r.requesterSettlementId===requesterId&&r.state==='PENDING'))return null;const representative=this.selectRepresentative(requesterId);if(!representative)return null;const request={id:`aid-request-${this.nextId++}`,requesterSettlementId:requesterId,targetSettlementId:targetId,resource:resource??need.resource,amount:3,state:'PENDING',representativeId:representative.id,cycle:this.world.worldTime?.cycle??0};this.requests.push(request);this.trace('aidRequested',request);this.world.dialogue?.say?.(new CommunicationIntent({speakerId:representative.id,targetType:'NEARBY_CHARACTER',intent:'REQUEST_SETTLEMENT_AID',resource:request.resource,settlementId:requesterId,priority:'HIGH'}));return request;}
  selectRepresentative(settlementId){const adults=this.world.characters.filter(c=>c.alive&&c.lifeStage==='adult'&&c.settlementId===settlementId&&!c.inCombat&&!c.foundingState);const settlement=this.world.settlements.find(s=>s.id===settlementId);return adults.sort((a,b)=>(b.id===settlement?.founderId)-(a.id===settlement?.founderId)||(b.isExalted?1:0)-(a.isExalted?1:0)||(b.reputation?.entries?.length??0)-(a.reputation?.entries?.length??0))[0]??null;}
  cultureValue(id,key){return this.world.settlements.find(s=>s.id===id)?.culture?.value?.(key)??0;}
  beliefCompatibility(aId,bId){const a=this.world.settlementBeliefs?.forSettlement?.(aId)?.dominant,b=this.world.settlementBeliefs?.forSettlement?.(bId)?.dominant;if(!a||!b)return 0;const aType=a.beliefType??a.type,bType=b.beliefType??b.type;if(!aType||!bType)return 0;return aType===bType?Math.min(1,Math.min(a.strength??1,b.strength??1)):0;}
  decideAid(request){const storage=this.settlementStorage(request.targetSettlementId),available=storage?.get(request.resource)??0;if(available<=1)return{outcome:'CANNOT_HELP',amount:0,reason:'SCARCITY'};const view=this.view(request.targetSettlementId,request.requesterSettlementId)??{trust:0,tension:0};const willingness=this.cultureValue(request.targetSettlementId,'COOPERATION')+this.cultureValue(request.targetSettlementId,'HOSPITALITY')*.6+view.trust/100-view.tension/80+this.beliefCompatibility(request.targetSettlementId,request.requesterSettlementId)*.15;if(willingness<-.15)return{outcome:'REFUSE',amount:0,reason:'DISTRUST'};const amount=Math.min(request.amount,available-1,willingness<.35?1:3);return{outcome:amount<request.amount?'PARTIAL_HELP':'ACCEPT',amount,reason:'SURPLUS'};}
  resolveRequest(request){const decision=this.decideAid(request);request.state=decision.outcome;request.reason=decision.reason;if(decision.amount>0){this.trace('aidAccepted',{requestId:request.id,outcome:decision.outcome,amount:decision.amount});return this.startAidDelivery(request.targetSettlementId,request.requesterSettlementId,request.resource,decision.amount,request.id);}const relation=this.relation(request.requesterSettlementId,request.targetSettlementId),unable=decision.outcome==='CANNOT_HELP';relation?.change(request.requesterSettlementId,{trust:unable?-1:-5,tension:unable?1:7});relation?.remember(request.requesterSettlementId,{type:unable?'AID_UNAVAILABLE':'AID_REFUSED',cycle:this.world.worldTime?.cycle??0,importance:unable?.35:.65,resource:request.resource,source:'REPRESENTATIVE'});this.trace('aidRefused',{requestId:request.id,outcome:decision.outcome,reason:decision.reason});return decision;}
  startAidDelivery(donorId,recipientId,resource,amount,requestId=null){const storage=this.settlementStorage(donorId),carrier=this.selectRepresentative(donorId),recipient=this.world.settlements.find(s=>s.id===recipientId);if(!storage||!carrier||!recipient||amount<1)return null;if(!this.eligibleTraveler(carrier,recipientId)||this.visits.some(v=>v.state!==SettlementVisit.States.COMPLETE&&v.state!==SettlementVisit.States.INTERRUPTED))return null;const removed=storage.remove(resource,Math.min(3,amount));if(!removed)return null;const delivery=new AidDelivery({id:`aid-delivery-${this.nextId++}`,requestId,donorSettlementId:donorId,recipientSettlementId:recipientId,carrierId:carrier.id,resource,amount:removed});const visit=this.startVisit(carrier,recipientId,'DELIVER_AID',delivery);if(!visit){storage.add(resource,removed);return null;}this.deliveries.push(delivery);this.trace('aidDeliveryStarted',{deliveryId:delivery.id,donorSettlementId:donorId,recipientSettlementId:recipientId,resource,amount:removed});return delivery;}
  eligibleTraveler(character,targetId){if(!character?.alive||character.lifeStage!=='adult'||!character.settlementId||character.settlementId===targetId||character.inCombat||character.foundingState)return false;const target=this.world.settlements.find(s=>s.id===targetId);return Boolean(target?.center&&new Pathfinder().findPath(this.world.terrain,character.position,target.center).length);}
  startVisit(character,targetId,purpose='SOCIAL_VISIT',delivery=null){if(!this.eligibleTraveler(character,targetId)||this.visits.some(v=>v.state!==SettlementVisit.States.COMPLETE&&v.state!==SettlementVisit.States.INTERRUPTED))return null;const cycle=this.world.worldTime?.cycle??0,key=this.key(character.settlementId,targetId);if(purpose!=='DELIVER_AID'&&cycle-(this.lastVisitCycle[key]??-99)<8)return null;const home=this.world.settlements.find(s=>s.id===character.settlementId),target=this.world.settlements.find(s=>s.id===targetId),visit=new SettlementVisit({id:`visit-${this.nextId++}`,characterId:character.id,homeSettlementId:character.settlementId,visitorSettlementId:targetId,purpose,targetPosition:target.center,homePosition:home.center,startedCycle:cycle});this.visits.push(visit);this.lastVisitCycle[key]=cycle;character.visitorSettlementId=targetId;character.visitPurpose=purpose;character.visitState=visit.state;if(delivery)delivery.visitId=visit.id;this.trace('visitorStarted',{visitId:visit.id,characterId:character.id,purpose});return visit;}
  startFamilyVisit(character,targetId){const family=this.world.characters.some(other=>other.alive&&other.settlementId===targetId&&(character.parentIds?.includes(other.id)||other.parentIds?.includes(character.id)||character.parentIds?.some(id=>other.parentIds?.includes(id))));return family?this.startVisit(character,targetId,'FAMILY_VISIT'):null;}
  move(character,target,deltaTime){const distance=Math.hypot(target.x-character.position.x,target.y-character.position.y);if(distance<=.45)return true;const step=Math.min(distance,deltaTime*2);character.position.x+=(target.x-character.position.x)/distance*step;character.position.y+=(target.y-character.position.y)/distance*step;return false;}
  updateVisit(visit,deltaTime){const character=this.world.characters.find(c=>c.id===visit.characterId);if(!character?.alive){visit.state=SettlementVisit.States.INTERRUPTED;const delivery=this.deliveries.find(d=>d.visitId===visit.id&&d.state===AidDelivery.States.TRAVELING);if(delivery)delivery.state=AidDelivery.States.LOST;return;}if(visit.state===SettlementVisit.States.TRAVELING&&this.move(character,visit.targetPosition,deltaTime)){visit.state=SettlementVisit.States.ARRIVED;character.visitState=visit.state;this.trace('visitorArrived',{visitId:visit.id,characterId:character.id});const delivery=this.deliveries.find(d=>d.visitId===visit.id);if(delivery)this.deliver(delivery);else this.world.dialogue?.say?.(new CommunicationIntent({speakerId:character.id,targetType:'NEARBY_CHARACTER',intent:'COMMENT_ON_SETTLEMENT',settlementId:visit.visitorSettlementId,priority:'NORMAL'}));}else if(visit.state===SettlementVisit.States.ARRIVED){visit.stayRemaining-=deltaTime;if(visit.stayRemaining<=0){visit.state=SettlementVisit.States.RETURNING;character.visitState=visit.state;}}else if(visit.state===SettlementVisit.States.RETURNING&&this.move(character,visit.homePosition,deltaTime)){visit.state=SettlementVisit.States.COMPLETE;character.visitorSettlementId=null;character.visitPurpose=null;character.visitState=null;const delivery=this.deliveries.find(d=>d.visitId===visit.id);if(delivery)delivery.state=AidDelivery.States.COMPLETE;this.trace('visitorReturned',{visitId:visit.id,characterId:character.id});}}
  deliver(delivery){if(delivery.state!==AidDelivery.States.TRAVELING)return false;const storage=this.settlementStorage(delivery.recipientSettlementId);if(!storage)return false;const added=storage.add(delivery.resource,delivery.amount);delivery.amount-=added;if(delivery.amount>0)return false;delivery.state=AidDelivery.States.DELIVERED;if(!delivery.rewardApplied){const relation=this.relation(delivery.donorSettlementId,delivery.recipientSettlementId),cycle=this.world.worldTime?.cycle??0;relation?.change(delivery.recipientSettlementId,{trust:10,cooperation:12,affinity:4,tension:-3});relation?.change(delivery.donorSettlementId,{cooperation:3,affinity:2});relation?.remember(delivery.recipientSettlementId,{type:'AID_DELIVERED',resource:delivery.resource,cycle,importance:.9,source:'WITNESSED',fromSettlementId:delivery.donorSettlementId});delivery.rewardApplied=true;}this.trace('aidDelivered',{deliveryId:delivery.id,resource:delivery.resource});return true;}
  recordTheft({victimSettlementId,thief,originKnown=false,amount=1,resource='food'}){if(!originKnown||!thief?.settlementId||thief.settlementId===victimSettlementId)return false;const relation=this.relation(victimSettlementId,thief.settlementId);if(!relation)return false;relation.change(victimSettlementId,{trust:-4,tension:Math.min(9,3+amount)});relation.remember(victimSettlementId,{type:'THEFT',cycle:this.world.worldTime?.cycle??0,importance:.65,resource,source:'WITNESSED',characterId:thief.id});this.trace('interSettlementTheft',{victimSettlementId,originSettlementId:thief.settlementId,characterId:thief.id});return true;}
  diffuseCulture(visit){const home=this.world.settlements.find(s=>s.id===visit.homeSettlementId),target=this.world.settlements.find(s=>s.id===visit.visitorSettlementId),custom=target?.culture?.customs?.find(value=>!home?.culture?.customs?.includes(value));if(!custom||visit.state!==SettlementVisit.States.COMPLETE)return false;const dimension=custom.includes('SHARE')?'COOPERATION':'HOSPITALITY';home.culture.dimensions[dimension]=Math.min(1,(home.culture.dimensions[dimension]??0)+.01);this.trace('cultureDiffused',{fromSettlementId:target.id,toSettlementId:home.id,custom});return true;}
  restoreCharacterVisitState(){for(const visit of this.visits.filter(v=>![SettlementVisit.States.COMPLETE,SettlementVisit.States.INTERRUPTED].includes(v.state))){const character=this.world.characters.find(c=>c.id===visit.characterId);if(character){character.visitorSettlementId=visit.visitorSettlementId;character.visitPurpose=visit.purpose;character.visitState=visit.state;}}}
  update(deltaTime){this.accumulator+=deltaTime;for(const visit of this.visits.filter(v=>![SettlementVisit.States.COMPLETE,SettlementVisit.States.INTERRUPTED].includes(v.state)))this.updateVisit(visit,deltaTime);if(this.accumulator<15)return;this.accumulator=0;this.ensureRelations();for(const relation of this.relationships)relation.decay(this.world.worldTime?.cycle??0);}
  toJSON(){return{relationships:this.relationships.map(r=>r.toJSON()),visits:this.visits.map(v=>v.toJSON()),deliveries:this.deliveries.map(d=>d.toJSON()),requests:this.requests.map(r=>({...r})),nextId:this.nextId,lastVisitCycle:{...this.lastVisitCycle}};}
}
