import { CommunicationIntent } from '../dialogue/CommunicationIntent.js';
export class CultureBehaviorSystem {
  constructor(world,data={}){this.world=world;this.cooldown=data.cooldown??0;}
  update(dt){this.cooldown=Math.max(0,this.cooldown-dt);if(this.cooldown||this.world.invasions?.enemies?.some(e=>e.alive))return;this.cooldown=8;for(const settlement of this.world.settlements){this.tryShare(settlement);const injured=this.world.characters.find(c=>c.alive&&c.injured&&c.settlementId===settlement.id);const helper=this.world.characters.find(c=>c.alive&&c.lifeStage==='adult'&&!c.injured&&c.id!==injured?.id&&c.settlementId===settlement.id);if(helper&&injured)this.helpInjured(helper,injured);}}
  tryShare(settlement,random=Math.random){if(!settlement.culture.hasCustom('SHARE_FOOD_IN_CRISIS'))return false;const homes=this.world.homes.filter(h=>h.settlementId===settlement.id&&h.storage);const donor=homes.find(h=>h.storage.get('food')>=4), recipient=homes.find(h=>h.id!==donor?.id&&h.storage.get('food')<=1&&!h.storage.isFull('food'));const character=this.world.characters.find(c=>c.alive&&c.lifeStage==='adult'&&c.homeBuildingId===donor?.id);if(!donor||!recipient||!character||random()>=this.world.cultures.probability(character,'SHARE_FOOD_IN_CRISIS',.08))return false;return this.shareFood(character,donor,recipient);}
  shareFood(character,donor,recipient){if(donor.settlementId!==recipient.settlementId||donor.storage.remove('food',1)!==1)return false;const added=recipient.storage.add('food',1);if(added!==1){donor.storage.add('food',1);return false;}this.world.cultures.addSignal(character.settlementId,'cooperation',1);this.world.dialogue?.say(new CommunicationIntent({speakerId:character.id,intent:'PRAISE_CUSTOM',custom:'SHARE_FOOD_IN_CRISIS',priority:'NORMAL'}));const witnesses=this.world.characters.filter(c=>c.id!==character.id&&c.alive&&c.settlementId===character.settlementId&&Math.hypot(c.position.x-character.position.x,c.position.y-character.position.y)<7);for(const witness of witnesses){witness.reputation.learn(character.id,'HELPFUL',{source:'WITNESSED'});this.world.diagnostics?.trace('reputationChanged',{observerId:witness.id,subjectId:character.id,label:'HELPFUL'});}return true;}
  helpInjured(helper,injured,random=Math.random){if(!injured?.injured||helper?.injured||helper?.settlementId!==injured.settlementId||random()>=this.world.cultures.probability(helper,'HELP_INJURED',.05))return false;injured.position={...this.world.homeFor(injured)?.position??injured.position};helper.reputation.learn(injured.id,'PROTECTIVE',{source:'WITNESSED',certainty:.7});this.world.cultures.addSignal(helper.settlementId,'cooperation',.6);return true;}
  protectionPriority(character,children=[]){const culture=this.world.settlements.find(s=>s.id===character.settlementId)?.culture;if(!culture?.hasCustom('PROTECT_CHILDREN_FIRST'))return null;return children.filter(c=>c.alive&&c.lifeStage==='child').sort((a,b)=>Math.hypot(a.position.x-character.position.x,a.position.y-character.position.y)-Math.hypot(b.position.x-character.position.x,b.position.y-character.position.y))[0]??null;}
  toJSON(){return {cooldown:this.cooldown};}
}
