import { Config } from '../core/Config.js';
import { CharacterRenderer } from './CharacterRenderer.js';
import { CharacterAssetRegistry } from '../assets/CharacterAssetRegistry.js';
import { AssetLoader } from '../assets/AssetLoader.js';
import { TerrainVisualRenderer } from './TerrainVisualRenderer.js';
import { MigrationNarrative } from '../data/MigrationNarrative.js';
import { RivalEventRenderer } from './RivalEventRenderer.js';
import { EnemyRenderer } from './EnemyRenderer.js';
import { Camera } from './Camera.js';
import { PresentationMode } from '../presentation/PresentationMode.js';

export class Renderer {
  constructor(canvas, windowObject = globalThis.window, registry = new CharacterAssetRegistry(), assetLoader = null, camera = null) {
    this.canvas = canvas;
    this.context = canvas.getContext('2d');
    this.window = windowObject;
    this.world = null;
    this.elapsed = 0;
    this.terrainVisualRenderer = null;
    this.assetRegistry = registry;
    this.assetLoader = assetLoader ?? new AssetLoader(registry);
    this.characterRenderer = new CharacterRenderer(this.context, registry, this.assetLoader);
    this.worldImages = new Map();
    this.rivalEventRenderer = new RivalEventRenderer(this.context, this.canvas, path => this.image(path));
    this.enemyRenderer = new EnemyRenderer(this.context);
    this.camera = camera ?? new Camera(canvas.width, canvas.height);
    this.renderDpr = 1;
  }

  setWorld(world) { this.world = world; this.camera.configure(world.terrain.width, world.terrain.height, this.canvas.width, this.canvas.height); this.buildTerrainLayer(); }
  update(deltaTime) { this.elapsed += deltaTime; }

  resize() {
    const bounds = this.canvas.getBoundingClientRect();
    const pixelRatio = Math.min(2, Math.max(1, this.window?.devicePixelRatio || 1));
    this.renderDpr = pixelRatio;
    const width = Math.max(1, Math.round(bounds.width * pixelRatio));
    const height = Math.max(1, Math.round(bounds.height * pixelRatio));
    if (this.canvas.width !== width || this.canvas.height !== height) {
      this.canvas.width = width; this.canvas.height = height;
    }
    this.camera.setViewport(width, height);
  }

  render() {
    if (!this.world?.terrain) { this.renderFoundation(); return; }
    this.drawBaseTerrain();
    this.drawWorldObjects();
    this.drawBuildings();
    this.drawCharacters();
    this.drawEnemies();
    this.drawProjectiles();
    this.drawMiracleEffects();
    this.drawTimeLighting();
    this.drawGameplayUI();
    this.drawInvasionPresentation();
    this.drawRivalAttack();
  }


  drawRivalAttack() {
    const event = this.world.rivalAttack;
    if (!event?.active) return;
    const target = this.worldPoint(event.targetPosition());
    const protectedPoints = this.world.characters.filter(character => character.alive && character.settlementId === event.targetSettlementId && (character.hasDivineShield || character.shieldImpactReaction > 0)).map(character => this.characterPoint(character));
    this.rivalEventRenderer.render(event, target, protectedPoints);
  }

  renderFoundation() {
    const { context, canvas } = this;
    context.fillStyle = Config.BACKGROUND_COLOR; context.fillRect(0, 0, canvas.width, canvas.height);
    context.fillStyle = '#e8e4dc'; context.textAlign = 'center';
    context.font = `${Math.max(18, canvas.height * 0.035)}px system-ui, sans-serif`;
    context.fillText('ELYSIA', canvas.width / 2, canvas.height / 2);
    context.font = `${Math.max(11, canvas.height * 0.018)}px system-ui, sans-serif`;
    context.fillText(Config.VERSION, canvas.width / 2, canvas.height / 2 + canvas.height * 0.05);
  }

  buildTerrainLayer() {
    const terrain = this.world?.terrain;
    const documentObject = this.canvas.ownerDocument ?? globalThis.document;
    if (!terrain || !documentObject?.createElement) return;
    this.terrainVisualRenderer = new TerrainVisualRenderer(documentObject, terrain, this.world.worldType, this.world.worldSeed);
  }

  drawBaseTerrain() {
    const { context, canvas } = this;
    if (this.presentationId === 'desktop') {
      context.fillStyle = this.world.worldType === 'human' ? '#397a91' : '#628852';
      context.fillRect(0, 0, canvas.width, canvas.height);
    } else context.clearRect(0, 0, canvas.width, canvas.height);
    const origin = this.camera.worldToScreen({ x: 0, y: 0 });
    const width = this.world.terrain.width * this.camera.zoom;
    const height = this.world.terrain.height * this.camera.zoom;
    this.terrainVisualRenderer?.drawStaticAt(context, origin.x, origin.y, width, height);
    context.save(); context.translate(origin.x, origin.y);
    this.terrainVisualRenderer?.drawDynamic(context, width, height, this.elapsed); context.restore();
    if (this.world.plantProgression?.triggered) { context.fillStyle = `rgba(15,8,20,${Math.min(.58, this.world.plantProgression.elapsed * .075)})`; context.fillRect(0, 0, canvas.width, canvas.height); }
  }

  screenToWorld(point) { return this.camera.screenToWorld(point); }
  worldPoint(position) { return this.camera.worldToScreen(position); }
  image(path) { if (!this.worldImages.has(path)) { const image = new Image(); image.src = path; this.worldImages.set(path, image); } return this.worldImages.get(path); }
  drawAsset(path, position, worldWidth, worldHeight, alpha = 1) { const image = this.image(path); if (!image.complete) return; const point = this.worldPoint(position); const width = worldWidth * this.camera.zoom; const height = worldHeight * this.camera.zoom; this.context.save(); this.context.globalAlpha = alpha; this.context.drawImage(image, point.x - width / 2, point.y - height * .82, width, height); this.context.restore(); }
  drawWorldObjects() { for (const tree of this.world.trees) this.drawAsset(tree.harvestable ? 'assets/entities/tree-healthy.svg' : 'assets/entities/tree-stump.svg', tree.position, 4.1, tree.harvestable ? 5.2 : 2.1); for (const source of this.world.waterSources.filter(e => e.alive)) this.drawAsset('assets/entities/water-source.svg', source.position, 3.5, 2.4); for (const cow of this.world.cows.filter(e => e.alive)) this.drawAsset('assets/entities/cow-idle.svg', cow.position, 4.8, 3.5); for (const food of this.world.animalFoodSources.filter(e => e.alive)) this.drawAsset('assets/entities/animal-food.svg', food.position, 3.8, 2.8); for (const flower of this.world.flowers) this.drawAsset('assets/entities/divine-flower.svg', flower.position, 2.2, 2.8); for (const tree of this.world.appleTrees) this.drawAsset('assets/entities/apple-tree.svg', tree.position, 4.8, 5.6, tree.availableFruit ? 1 : .78); }
  drawBuildings() { for (const home of this.world.homes) { const central = home.kind === 'centralStructure'; const beast = home.visualVariant?.includes('Den') || home.visualVariant?.startsWith('den') || home.visualVariant?.startsWith('establishedDen'); const path = central ? (beast ? 'assets/entities/great-den.svg' : 'assets/entities/castle.svg') : beast ? 'assets/entities/established-den.svg' : home.kind === 'house' ? 'assets/entities/house.svg' : 'assets/entities/hut.svg'; this.drawAsset(path, home.position, central ? 11 : 8, central ? 8 : 6.4, home.completed ? 1 : Math.max(.25, home.buildProgress)); if (home.transformationAge < 1.4) this.drawTransformation(home); } }
  drawMiracleEffects() { for (const effect of this.world.effects) { if (effect.type === 'intimacy') { this.drawIntimacyHearts(effect); continue; } if (effect.type === 'newLife') { this.drawNewLifeEffect(effect); continue; } if(effect.type==='lifeBloom'||effect.type==='lifeBloomEmergence'){this.drawLifeBloom(effect);continue;} if(effect.type==='identityReveal'){this.drawIdentityReveal(effect);continue;} const point = this.worldPoint(effect.position); if (['lightning','blessing','rayOfLight','flowerGrowth','exalted','changeSex','giveWeapons','shield'].includes(effect.type)) { this.drawDivineEffect(effect); continue; } const radius = (12 + effect.age * 35) * (this.canvas.width / 1200); this.context.save(); this.context.globalAlpha = 1 - effect.age / .8; this.context.strokeStyle = effect.type === 'valid' ? '#fff1a8' : '#ef8d79'; this.context.lineWidth = 3; this.context.beginPath(); this.context.arc(point.x, point.y, radius, 0, Math.PI * 2); this.context.stroke(); this.context.restore(); } }
  drawIdentityReveal(effect){const p=this.worldPoint(effect.position),c=this.context,t=Math.min(1,effect.age/(effect.duration??2));c.save();c.globalCompositeOperation='screen';c.globalAlpha=Math.sin(t*Math.PI);const glow=c.createRadialGradient(p.x,p.y,2,p.x,p.y,80);glow.addColorStop(0,'rgba(255,255,236,.95)');glow.addColorStop(.45,'rgba(133,225,255,.42)');glow.addColorStop(1,'rgba(119,164,255,0)');c.fillStyle=glow;c.beginPath();c.arc(p.x,p.y,80,0,Math.PI*2);c.fill();for(let i=0;i<12;i++){const a=i*.83+effect.age*2,r=18+t*55;c.fillStyle=i%2?'#fff4b8':'#b8f2ff';c.beginPath();c.arc(p.x+Math.cos(a)*r,p.y+Math.sin(a)*r,2.5,0,Math.PI*2);c.fill();}c.restore();}
  drawLifeBloom(effect){const p=this.worldPoint(effect.position),c=this.context,t=Math.min(1,effect.age/3.6),fade=Math.max(0,1-Math.max(0,effect.age-4.4)/.8);c.save();c.globalAlpha=fade;const glow=c.createRadialGradient(p.x,p.y,1,p.x,p.y,75);glow.addColorStop(0,'rgba(255,242,160,.62)');glow.addColorStop(1,'rgba(255,209,108,0)');c.fillStyle=glow;c.fillRect(p.x-80,p.y-70,160,100);c.strokeStyle='#79ad63';c.lineWidth=5;c.beginPath();c.moveTo(p.x,p.y);c.quadraticCurveTo(p.x-5,p.y-28*t,p.x,p.y-55*t);c.stroke();if(t>.3){c.fillStyle='#79ad63';c.beginPath();c.ellipse(p.x-9,p.y-25*t,12*t,5*t,-.5,0,Math.PI*2);c.ellipse(p.x+10,p.y-34*t,12*t,5*t,.5,0,Math.PI*2);c.fill();}if(t>.62){const open=Math.min(1,(t-.62)/.38);for(let i=0;i<10;i++){const a=i*Math.PI/5;c.fillStyle=i%2?'#ffd99d':'#fff2c0';c.beginPath();c.ellipse(p.x+Math.cos(a)*17*open,p.y-55*t+Math.sin(a)*10*open,16*open,7*open,a,0,Math.PI*2);c.fill();}c.fillStyle='#fff6b0';c.beginPath();c.arc(p.x,p.y-55*t,8*open,0,Math.PI*2);c.fill();}for(let i=0;i<9;i++){const a=i*1.7+effect.age,r=18+(i%3)*12;c.globalAlpha=fade*(.35+.5*Math.sin(effect.age*3+i)**2);c.fillStyle='#fff2ad';c.beginPath();c.arc(p.x+Math.cos(a)*r,p.y-25-Math.sin(a)*r*.6,2,0,Math.PI*2);c.fill();}c.restore();}
  drawDivineEffect(effect) { const p=this.worldPoint(effect.position),c=this.context,a=Math.max(0,1-effect.age/(effect.duration??1.6)); c.save(); c.globalCompositeOperation='screen'; c.globalAlpha=a; if(effect.type==='lightning'){c.strokeStyle='#eaf5ff';c.shadowColor='#8fd8ff';c.shadowBlur=18;c.lineWidth=5;c.beginPath();c.moveTo(p.x-18,0);c.lineTo(p.x+9,p.y-75);c.lineTo(p.x-6,p.y);c.stroke();} else if(effect.type==='rayOfLight'){const g=c.createLinearGradient(p.x,p.y-300,p.x,p.y);g.addColorStop(0,'rgba(255,255,240,0)');g.addColorStop(.5,'rgba(255,244,174,.5)');g.addColorStop(1,'rgba(255,231,138,.8)');c.fillStyle=g;c.beginPath();c.moveTo(p.x-24,p.y);c.lineTo(p.x-80,p.y-320);c.lineTo(p.x+80,p.y-320);c.lineTo(p.x+24,p.y);c.fill();} else {const color=effect.type==='blessing'||effect.type==='exalted'?'255,224,125':'204,230,255';const g=c.createRadialGradient(p.x,p.y,2,p.x,p.y,70);g.addColorStop(0,`rgba(${color},.8)`);g.addColorStop(1,`rgba(${color},0)`);c.fillStyle=g;c.beginPath();c.arc(p.x,p.y,70,0,Math.PI*2);c.fill();} c.restore(); }
  drawIntimacyHearts(effect) { const origin=this.worldPoint(effect.position); const context=this.context; const standardSets=[['♥','♂','♀','♥'],['♥','♥','⚥','♥'],['⚥','♥','♀','♂'],['♥','⚥','♥','♥']]; const familySets=[['♥','✦','★','♥'],['✧','♥','♥','★'],['★','✦','♥','✧'],['♥','★','✦','♥']]; const sets=this.presentationMode===PresentationMode.FAMILY?familySets:standardSets; const symbols=sets[(effect.visualVariant ?? 0)%sets.length]; for(let index=0;index<symbols.length;index+=1){const age=Math.max(0,effect.age-index*.32);if(age<=0)continue;const x=origin.x+Math.sin(age*2.4+index)*22;const y=origin.y-45-age*20;context.save();context.globalAlpha=Math.max(0,1-age/3.2);context.fillStyle=index%2?'#f4a0a0':'#d95e76';context.shadowColor='#ffd0bd';context.shadowBlur=8;context.font=`${12+index*2}px Georgia`;context.textAlign='center';context.fillText(symbols[index],x,y);context.restore();} }
  drawNewLifeEffect(effect) { const point=this.worldPoint(effect.position); const context=this.context; const pulse=Math.sin(Math.min(1,effect.age/2)*Math.PI); const radius=(45+effect.age*16)*(this.canvas.width/1200); context.save(); context.globalCompositeOperation='screen'; context.globalAlpha=Math.max(0,1-effect.age/6); const glow=context.createRadialGradient(point.x,point.y,2,point.x,point.y,radius); glow.addColorStop(0,`rgba(255,247,189,${.7*pulse})`); glow.addColorStop(.45,'rgba(245,201,113,.28)'); glow.addColorStop(1,'rgba(245,201,113,0)'); context.fillStyle=glow; context.beginPath(); context.arc(point.x,point.y,radius,0,Math.PI*2); context.fill(); context.restore(); }
  drawTimeLighting() { if (!this.world.worldTime || this.world.worldType === 'plant') return; const { phase, progress } = this.world.worldTime.lighting(); const context = this.context; let color = 'rgba(0,0,0,0)'; if (phase === 'dusk') color = `rgba(117,54,91,${.08 + progress * .2})`; if (phase === 'night') color = `rgba(12,31,75,${.34 + Math.sin(progress * Math.PI) * .08})`; if (phase === 'dawn') color = `rgba(238,143,103,${.2 * (1-progress)})`; context.save(); context.fillStyle = color; context.globalCompositeOperation = 'multiply'; context.fillRect(0,0,this.canvas.width,this.canvas.height); if (phase === 'night') { const glow=context.createRadialGradient(this.canvas.width*.78,this.canvas.height*.15,2,this.canvas.width*.78,this.canvas.height*.15,this.canvas.width*.28); glow.addColorStop(0,'rgba(174,211,255,.2)'); glow.addColorStop(1,'rgba(174,211,255,0)'); context.globalCompositeOperation='screen'; context.fillStyle=glow; context.fillRect(0,0,this.canvas.width,this.canvas.height); } context.restore(); }
  drawHomeOccupancy(beast) { const point=this.worldPoint(this.world.hut.position); const context=this.context; const radius=(beast?34:45)*(this.canvas.width/1200); const glow=context.createRadialGradient(point.x,point.y-8,0,point.x,point.y-8,radius); glow.addColorStop(0,beast?'rgba(226,157,86,.34)':'rgba(255,190,82,.62)'); glow.addColorStop(1,'rgba(255,170,60,0)'); context.save(); context.globalCompositeOperation='screen'; context.fillStyle=glow; context.beginPath(); context.arc(point.x,point.y-8,radius,0,Math.PI*2); context.fill(); context.restore(); }
  drawGameplayUI() { if (this.world.hut?.completed) { const point = this.worldPoint(this.world.hut.position); const storage = this.world.hut.storage; this.context.save(); this.context.fillStyle = 'rgba(8,18,22,.82)'; this.context.fillRect(point.x - 88, point.y + 12, 176, 28); this.context.fillStyle = '#f7e9b7'; this.context.textAlign = 'center'; this.context.font = '11px system-ui'; this.context.fillText(`Legno ${storage.get('wood')}/${storage.capacity}  Acqua ${storage.get('water')}/${storage.capacity}  Cibo ${storage.get('food')}/${storage.capacity}`, point.x, point.y + 30); const household = this.world.households[0]; if (household) { const names = household.memberIds.map(id => this.world.characters.find(c => c.id === id)).filter(c => c?.alive).slice(0,2).map(c => c.name); this.context.font = '600 12px Georgia'; this.context.fillText(names.join(' & ').toLocaleUpperCase('it'), point.x, point.y - 55); } this.context.restore(); } for (const character of this.world.characters.filter(item => !item.insideHome)) { const ai = this.world.ais.get(character.id); if (!ai) continue; const point = this.characterPoint(character); this.context.save(); this.context.fillStyle = 'rgba(7,16,20,.7)'; this.context.font = '11px system-ui'; this.context.textAlign = 'center'; this.context.fillText(ai.status(), point.x, point.y - 42); this.context.restore(); } this.drawTimeIndicator(); this.drawCharacterInfo(); this.drawHomeInfo(); this.drawSpeechBubble(); this.drawLifeBloomNarration(); this.drawMealPresentation(); this.drawSettlementTransformation(); this.drawNewLifeMessage(); this.drawPlantEnding(); }
  drawLifeBloomNarration(){const effect=this.world.effects.find(item=>item.type==='lifeBloom');if(!effect)return;const c=this.context,alpha=Math.min(1,effect.age*1.5,(effect.duration??5.2)-effect.age);c.save();c.globalAlpha=Math.max(0,alpha);c.fillStyle='rgba(8,13,29,.68)';c.fillRect(this.canvas.width*.1,this.canvas.height*.1,this.canvas.width*.8,64);c.fillStyle='#fff3c4';c.shadowColor='#f1c66c';c.shadowBlur=12;c.textAlign='center';c.font='italic 17px Georgia';c.fillText(effect.message,this.canvas.width/2,this.canvas.height*.1+39);c.restore();}
  drawTimeIndicator() { if (!this.world.worldTime || this.world.worldType === 'plant') return; const labels={day:'GIORNO',dusk:'TRAMONTO',night:'NOTTE',dawn:'ALBA'}; const context=this.context; context.save(); context.fillStyle='rgba(7,17,29,.76)'; context.beginPath(); context.roundRect(18,this.canvas.height-92,112,30,15); context.fill(); context.fillStyle='#f7e8b4'; context.font='600 11px system-ui'; context.textAlign='center'; context.fillText(`${this.world.worldTime.phase==='night'?'☾':'☼'}  ${labels[this.world.worldTime.phase]}`,74,this.canvas.height-73); context.restore(); }
  drawHomeInfo() { const home = this.world.findHome(this.world.selectedBuildingId); if (!home) return; const settlement = this.world.settlements.find(item => item.id === home.settlementId); const household=this.world.households.find(item=>item.homeBuildingId===home.id); const members=(household?.memberIds ?? []).map(id=>this.world.characters.find(character=>character.id===id)).filter(character=>character?.alive); const founder=this.world.characters.find(character=>character.id===settlement?.founderId); const population=settlement ? this.world.characters.filter(character=>character.alive && character.settlementId===settlement.id).length : members.length; const lines=[settlement?.name ?? (home.visualVariant?.includes('den')?'Tana familiare':'Casa familiare')]; if (settlement) { lines.push(`Fondatore: ${founder?.name ?? 'Sconosciuto'}`,`Popolazione: ${population}`,`Stato: ${settlement.state === 'ESTABLISHED' ? 'STABILITO' : 'IN CRESCITA'}`); if (settlement.state === 'GROWING') lines.push(`Arrivi esterni: ${settlement.externalArrivalCount} / 4`); } lines.push('Abitanti:',...members.map(member=>`${member.name}${member.lifeStage==='child'?' — bambino':''}`)); const context=this.context; context.save(); context.fillStyle='rgba(7,14,20,.92)'; context.strokeStyle='#b99d68'; context.fillRect(18,18,350,24+lines.length*20); context.strokeRect(18,18,350,24+lines.length*20); context.fillStyle='#f4e7bd'; context.textAlign='left'; lines.forEach((line,index)=>{context.font=index===0?'600 17px Georgia':'12px system-ui';context.fillText(line,34,46+index*20);}); context.restore(); }

  drawCharacterInfo() { const character = this.world.characters.find(item => item.id === this.world.selectedCharacterId); if (!character) return; const ai = this.world.ais.get(character.id); const household = this.world.households.find(item => item.id === character.householdId); const native = character.originWorld === 'ELYSIA'; const lines = [character.name, character.chosenOne ? 'Prescelto di Elysia' : 'Abitante di Elysia', native ? (character.birthCycle === null ? 'ORIGINARIO DI ELYSIA' : 'Nato su Elysia.') : `PROVENIENTE DA ${character.originWorld}`, ai?.status() ?? 'In attesa', household ? `Casa: ${household.id}` : 'Senza dimora']; if (!native) { lines.push(`Arrivato su Elysia: Giorno ${character.arrivalCycle ?? '?'}`); lines.push(`Storia: ${new MigrationNarrative().label(character.arrivalStoryType)}`); } if (this.presentationMode !== PresentationMode.FAMILY && character.genderIdentity) lines.push(`Identità: ${character.genderIdentity} · Orientamento: ${character.sexualOrientation}`); const context = this.context; context.save(); context.fillStyle='rgba(7,14,20,.9)'; context.strokeStyle='#b99d68'; context.lineWidth=1; context.fillRect(18,18,390,22+lines.length*21); context.strokeRect(18,18,390,22+lines.length*21); context.fillStyle='#f4e7bd'; context.textAlign='left'; lines.forEach((line,index)=>{ context.font=index===0?'600 17px Georgia':'12px system-ui'; context.fillText(line,34,46+index*21); }); context.restore(); }

  drawTransformation(building) { const point = this.worldPoint(building.position); const progress = building.transformationAge / 1.4; const context = this.context; context.save(); context.globalAlpha = 1 - progress; const glow = context.createRadialGradient(point.x, point.y, 4, point.x, point.y, 90); glow.addColorStop(0, '#fffbd5dd'); glow.addColorStop(.45, '#f4c76e66'); glow.addColorStop(1, '#f4c76e00'); context.fillStyle = glow; context.beginPath(); context.arc(point.x, point.y, 90, 0, Math.PI * 2); context.fill(); context.restore(); }
  drawSpeechBubble() { const progression = this.world.householdProgression; const newcomer = this.world.characters.find(character => (character.speechRemaining ?? 0) > 0 && character.newcomer); const speaker = newcomer ?? (progression?.state === 'speaking' ? progression.partner : null); if (!speaker) return; const text = newcomer?.speechText ?? progression.speechText(); const point = this.characterPoint(speaker); const context = this.context; const width = Math.min(430, this.canvas.width * .58); const x = Math.max(width / 2 + 10, Math.min(this.canvas.width - width / 2 - 10, point.x)); const y = Math.max(76, Math.min(this.canvas.height - 88, point.y - 90)); context.save(); context.fillStyle = 'rgba(255,248,220,.98)'; context.strokeStyle = '#8f7446'; context.lineWidth = 2; context.beginPath(); context.roundRect(x-width/2, y-42, width, 70, 14); context.fill(); context.stroke(); context.fillStyle = '#30251c'; context.font = 'italic 14px Georgia'; context.textAlign = 'center'; const split = text.length > 52 ? text.lastIndexOf(' ', 52) : -1; if (split > 0) { context.fillText(text.slice(0, split), x, y - 9); context.fillText(text.slice(split + 1), x, y + 13); } else context.fillText(text, x, y + 2); context.restore(); }
  drawSettlementTransformation() { const effect = this.world.effects.find(item => item.type === 'settlementTransform'); if (!effect) return; const context = this.context; const alpha = Math.min(1, effect.age * 2, (effect.duration ?? 5) - effect.age); const point = this.worldPoint(effect.position); context.save(); context.globalAlpha = Math.max(0, alpha); const glow = context.createRadialGradient(point.x, point.y, 4, point.x, point.y, 150); glow.addColorStop(0, 'rgba(255,246,181,.64)'); glow.addColorStop(1, 'rgba(255,215,105,0)'); context.fillStyle = glow; context.fillRect(point.x-160, point.y-160, 320, 320); context.fillStyle = 'rgba(7,14,24,.82)'; context.fillRect(this.canvas.width*.12, this.canvas.height*.1, this.canvas.width*.76, 92); context.textAlign = 'center'; context.fillStyle = '#fff0b8'; context.font = '600 20px Georgia'; context.fillText(effect.settlementName, this.canvas.width/2, this.canvas.height*.1+34); context.font = 'italic 16px Georgia'; context.fillText(effect.message, this.canvas.width/2, this.canvas.height*.1+65); context.restore(); }
  drawMealPresentation() { const meal=this.world.meals; if (!meal?.speechText || !meal.partner) return; const point=this.characterPoint(meal.partner); const context=this.context; context.save(); context.fillStyle='rgba(255,248,220,.98)'; context.strokeStyle='#8f7446'; context.lineWidth=2; context.beginPath(); context.roundRect(point.x-58,point.y-92,116,44,13); context.fill(); context.stroke(); context.fillStyle='#30251c'; context.font='italic 600 15px Georgia'; context.textAlign='center'; context.fillText(meal.speechText,point.x,point.y-65); if (meal.partner.carryingMeal==='pot') { context.fillStyle='#5d3929'; context.beginPath(); context.ellipse(point.x+24,point.y-20,11,7,0,0,Math.PI*2); context.fill(); context.strokeStyle='#d3a56a'; context.beginPath(); context.moveTo(point.x+13,point.y-22); context.lineTo(point.x+35,point.y-22); context.stroke(); } context.restore(); }
  drawNewLifeMessage() { const effect=this.world.effects.find(item=>item.type==='newLife'); if (!effect) return; const context=this.context; const alpha=Math.min(1,effect.age*1.5,6-effect.age); context.save(); context.globalAlpha=Math.max(0,alpha); context.fillStyle='rgba(8,13,29,.38)'; context.fillRect(0,0,this.canvas.width,this.canvas.height); const width=Math.min(820,this.canvas.width*.82); const x=this.canvas.width/2; const y=this.canvas.height*.22; const glow=context.createRadialGradient(x,y,10,x,y,width*.55); glow.addColorStop(0,'rgba(255,231,156,.25)'); glow.addColorStop(1,'rgba(255,231,156,0)'); context.fillStyle=glow; context.fillRect(x-width*.6,y-90,width*1.2,180); context.fillStyle='#fff3c4'; context.shadowColor='#f1c66c'; context.shadowBlur=16; context.textAlign='center'; context.font=`italic ${Math.max(16,this.canvas.width*.018)}px Georgia`; const divider=effect.message.indexOf(',')+1; context.fillText(effect.message.slice(0,divider),x,y-6); context.fillText(effect.message.slice(divider).trim(),x,y+27); context.restore(); }
  drawPlantEnding() { const progression = this.world.plantProgression; if (!progression?.triggered) return; const context = this.context; const phase = progression.phase(); if (phase === 'rival') { context.save(); context.textAlign = 'center'; context.fillStyle = '#eee4ff'; context.shadowColor = '#aa8eff'; context.shadowBlur = 18; context.font = `400 ${Math.max(20, this.canvas.width*.026)}px Georgia`; context.fillText('« Interessante. Hai scelto un mondo incapace di difendersi. »', this.canvas.width/2, this.canvas.height*.2); context.restore(); } if (phase === 'meteor' || phase === 'impact') { const target = this.worldPoint({ x: this.world.terrain.width/2, y: this.world.terrain.height/2 }); const t = Math.min(1, Math.max(0, (progression.elapsed-3.3)/1.9)); const start = { x: this.canvas.width*1.08, y: -80 }; const meteor = { x: start.x+(target.x-start.x)*t, y:start.y+(target.y-start.y)*t }; context.save(); const gradient = context.createLinearGradient(start.x,start.y,meteor.x,meteor.y); gradient.addColorStop(0,'rgba(255,80,20,0)'); gradient.addColorStop(1,'#ffd08a'); context.strokeStyle=gradient; context.lineWidth=22; context.beginPath(); context.moveTo(start.x,start.y); context.lineTo(meteor.x,meteor.y); context.stroke(); context.fillStyle='#fff1bd'; context.shadowColor='#ff5b24'; context.shadowBlur=28; context.beginPath(); context.arc(meteor.x,meteor.y,14,0,Math.PI*2); context.fill(); if (phase==='impact') { const radius=(progression.elapsed-5.2)*180; context.strokeStyle='#ffe9bd'; context.lineWidth=12; context.globalAlpha=Math.max(0,1-radius/360); context.beginPath(); context.arc(target.x,target.y,radius,0,Math.PI*2); context.stroke(); context.fillStyle=`rgba(255,225,180,${Math.max(0,.8-radius/300)})`; context.fillRect(0,0,this.canvas.width,this.canvas.height); } context.restore(); } }

  characterPoint(character) {
    return this.worldPoint({ x: character.position.x + 0.5, y: character.position.y + 0.5 });
  }

  drawCharacters() {
    for (const character of this.world.characters.filter(item => item.alive && !item.insideHome)) {
      const point = this.characterPoint(character);
      const pixelsPerWorldUnit = this.camera.zoom;
      this.characterRenderer.render(character, point, this.elapsed, pixelsPerWorldUnit);
    }
  }
  drawEnemies() { const scale=this.camera.zoom;for(const enemy of this.world.invasions.enemies.filter(e=>e.alive))this.enemyRenderer.render(enemy,this.worldPoint(enemy.position),scale,this.elapsed); }
  drawProjectiles() { const c=this.context;for(const projectile of this.world.projectiles.projectiles.filter(p=>p.alive)){const p=this.worldPoint(projectile.position),angle=Math.atan2(projectile.velocity.y,projectile.velocity.x);c.save();c.translate(p.x,p.y);c.rotate(angle);if(projectile.type==='arrow'){c.strokeStyle='#432b1b';c.lineWidth=2;c.beginPath();c.moveTo(-10,0);c.lineTo(10,0);c.stroke();c.fillStyle='#d2c19d';c.beginPath();c.moveTo(10,0);c.lineTo(4,-4);c.lineTo(4,4);c.fill();}else{c.fillStyle='#63efff';c.shadowColor='#e541df';c.shadowBlur=12;c.beginPath();c.ellipse(0,0,12,4,0,0,Math.PI*2);c.fill();}c.restore();} }
  drawInvasionPresentation() { const invasion=this.world.invasions;if(!invasion)return;const c=this.context;for(const enemy of invasion.enemies.filter(e=>e.alive)){const p=this.worldPoint(enemy.position),ratio=enemy.health/enemy.type.baseHealth;c.fillStyle='rgba(20,12,18,.8)';c.fillRect(p.x-18,p.y-52,36,4);c.fillStyle=enemy.rivalWorldId==='rivalWorld1'?'#d89a45':enemy.rivalWorldId==='rivalWorld2'?'#b9dbef':'#5cf3ef';c.fillRect(p.x-18,p.y-52,36*ratio,4);}const intro=invasion.introduction;if(!intro)return;c.save();c.fillStyle='rgba(5,10,20,.88)';c.fillRect(this.canvas.width*.13,this.canvas.height*.08,this.canvas.width*.74,96);c.strokeStyle='#c9a76a';c.strokeRect(this.canvas.width*.13,this.canvas.height*.08,this.canvas.width*.74,96);c.textAlign='center';c.fillStyle='#f8eac5';c.font='600 20px Georgia';c.fillText(intro[0],this.canvas.width/2,this.canvas.height*.08+34);c.font='italic 15px Georgia';c.fillText(intro[1],this.canvas.width/2,this.canvas.height*.08+67);c.restore(); }

}
