import { FirstRivalAttack } from '../events/FirstRivalAttack.js';

export class RivalEventRenderer {
  constructor(context, canvas, imageProvider) { this.context=context; this.canvas=canvas; this.imageProvider=imageProvider; }
  render(event, target, characterPoints = []) { if (!event?.active) return; this.sky(event); if ([FirstRivalAttack.Phases.MANIFESTATION,FirstRivalAttack.Phases.DIALOGUE,FirstRivalAttack.Phases.WARNING,FirstRivalAttack.Phases.PREPARATION].includes(event.phase)) this.rival(event); if ([FirstRivalAttack.Phases.PREPARATION,FirstRivalAttack.Phases.METEOR,FirstRivalAttack.Phases.CASTLE_RESCUE,FirstRivalAttack.Phases.IMPACT].includes(event.phase)) this.meteor(event,target); if ([FirstRivalAttack.Phases.CASTLE_RESCUE,FirstRivalAttack.Phases.IMPACT,FirstRivalAttack.Phases.AFTERMATH].includes(event.phase)) this.rescue(event,target); if (event.phase===FirstRivalAttack.Phases.IMPACT) this.shockwave(event,target,characterPoints); this.text(event); }
  sky(event) { const c=this.context, strength=Math.min(.72,.18+event.elapsed*.08); const g=c.createRadialGradient(this.canvas.width*.72,this.canvas.height*.12,10,this.canvas.width*.72,this.canvas.height*.12,this.canvas.width*.75); g.addColorStop(0,`rgba(80,28,117,${strength})`); g.addColorStop(.45,'rgba(13,8,31,.58)'); g.addColorStop(1,'rgba(3,8,18,.35)'); c.save();c.fillStyle=g;c.fillRect(0,0,this.canvas.width,this.canvas.height);c.restore(); }
  rival(event) { const c=this.context,x=this.canvas.width*.72,y=this.canvas.height*.25,p=1+Math.sin(event.elapsed*2)*.04;c.save();c.globalCompositeOperation='screen';const aura=c.createRadialGradient(x,y,8,x,y,this.canvas.height*.29);aura.addColorStop(0,'rgba(158,92,255,.42)');aura.addColorStop(.5,'rgba(72,28,120,.2)');aura.addColorStop(1,'rgba(42,10,82,0)');c.fillStyle=aura;c.fillRect(x-this.canvas.height*.3,y-this.canvas.height*.3,this.canvas.height*.6,this.canvas.height*.6);c.globalCompositeOperation='source-over';c.fillStyle='rgba(5,5,18,.94)';c.beginPath();c.ellipse(x,y+55*this.canvas.height/700,90*p,150*p,0,0,Math.PI*2);c.fill();c.fillStyle='#f2e6ff';c.shadowColor='#b976ff';c.shadowBlur=25;c.beginPath();c.ellipse(x-28,y-8,10,4,-.12,0,Math.PI*2);c.ellipse(x+28,y-8,10,4,.12,0,Math.PI*2);c.fill();c.restore(); }
  meteor(event,target) { const c=this.context;let t=event.phase===FirstRivalAttack.Phases.PREPARATION?event.elapsed/20:event.phase===FirstRivalAttack.Phases.METEOR ? .55+event.elapsed/6 : .96;t=Math.min(.98,t);const start={x:this.canvas.width*1.05,y:-70},p={x:start.x+(target.x-start.x)*t,y:start.y+(target.y-start.y)*t};c.save();c.strokeStyle='rgba(255,100,43,.75)';c.shadowColor='#ff542d';c.shadowBlur=28;c.lineWidth=28;c.beginPath();c.moveTo(start.x,start.y);c.lineTo(p.x,p.y);c.stroke();const g=c.createRadialGradient(p.x,p.y,2,p.x,p.y,25);g.addColorStop(0,'#fff6cf');g.addColorStop(.3,'#ffbd60');g.addColorStop(1,'#7d1c2c');c.fillStyle=g;c.beginPath();c.arc(p.x,p.y,22,0,Math.PI*2);c.fill();c.restore(); }
  rescue(event,target) { const c=this.context, fade=event.phase===FirstRivalAttack.Phases.AFTERMATH?Math.max(0,1-event.elapsed/5):1;c.save();c.globalAlpha=fade;c.lineCap='round';const colors=['#ef5b72','#f4a64a','#ffe16b','#6fe09a','#64bdf1','#9b78e8'];colors.forEach((color,i)=>{c.strokeStyle=color;c.lineWidth=8;c.beginPath();c.arc(target.x,target.y+38,95+i*7,Math.PI*1.08,Math.PI*1.92);c.stroke();});const image=this.imageProvider('assets/entities/cosmic-unicorn.svg');if(image.complete){const run=Math.min(1,event.elapsed/2.4),x=target.x-100+run*200,y=target.y-80-Math.sin(run*Math.PI)*55;c.drawImage(image,x-48,y-42,96,84);}c.restore(); }
  shockwave(event,target,points) { const c=this.context,r=event.elapsed*230;c.save();c.strokeStyle='#fff0bd';c.shadowColor='#ff8b42';c.shadowBlur=30;c.lineWidth=12;c.globalAlpha=Math.max(0,1-event.elapsed/2.2);c.beginPath();c.arc(target.x,target.y,r,0,Math.PI*2);c.stroke();for(const p of points){c.strokeStyle='#bff4ff';c.lineWidth=5;c.beginPath();c.arc(p.x,p.y,25+event.elapsed*8,0,Math.PI*2);c.stroke();}c.restore(); }
  text(event) { const c=this.context;let message=null;if(event.phase===FirstRivalAttack.Phases.DIALOGUE)message=event.dialogueBeat();if(event.phase===FirstRivalAttack.Phases.WARNING)message='Il cielo sopra il primo insediamento si spezza.';if(event.phase===FirstRivalAttack.Phases.PREPARATION)message=`Proteggi chi vuoi salvare.   ${event.countdown}`;if(event.phase===FirstRivalAttack.Phases.AFTERMATH)message=event.elapsed<2?'« Vediamo quanto a lungo riuscirai a custodirli. »':event.aftermathMessage();if(!message)return;c.save();c.fillStyle='rgba(4,7,19,.86)';c.fillRect(this.canvas.width*.08,this.canvas.height*.07,this.canvas.width*.84,82);c.fillStyle='#fff0d0';c.shadowColor='#9d72d8';c.shadowBlur=12;c.textAlign='center';c.font=`600 ${Math.max(17,this.canvas.width*.018)}px Georgia`;c.fillText(message,this.canvas.width/2,this.canvas.height*.07+48);c.restore(); }
}
