import { PersonalBeliefs } from './PersonalBeliefs.js';

export class BeliefSystem {
  static Types = Object.freeze({ THEFT: 'THE_OMNIPOTENT_DISAPPROVES_OF_THEFT', SHARING: 'THE_OMNIPOTENT_APPROVES_OF_SHARING', CHILDREN: 'THE_OMNIPOTENT_PROTECTS_CHILDREN', STRENGTH: 'THE_OMNIPOTENT_VALUES_STRENGTH', OBEDIENCE: 'THE_OMNIPOTENT_REWARDS_OBEDIENCE', PROVIDES: 'THE_OMNIPOTENT_PROVIDES_WHEN_WE_SUFFER', VIOLENCE: 'THE_OMNIPOTENT_PUNISHES_VIOLENCE', FAVORS: 'THE_OMNIPOTENT_FAVORS_SOME_PEOPLE', UNPREDICTABLE: 'THE_OMNIPOTENT_IS_UNPREDICTABLE', ABANDONED: 'THE_OMNIPOTENT_HAS_ABANDONED_US', CASTLE_PROTECTED: 'THE_CASTLE_IS_PROTECTED', ELYSIA_CHOSEN: 'ELYSIA_IS_CHOSEN', SETTLEMENT_SAVED: 'THE_OMNIPOTENT_SAVED_THE_SETTLEMENT' });
  constructor(world) { this.world = world; this.firstBeliefNotified = new Set(); this.firstTeachingNotified = new Set(); }
  observe(character, memory, interpretation = {}) { if (!character || character.lifeStage === 'child' || !memory?.id) return null; const type = interpretation.beliefType ?? this.infer(character, memory, interpretation); if (!type) return null; const source = interpretation.sourceType ?? (memory.participants?.includes(character.id) ? PersonalBeliefs.Sources.PERSONAL_EXPERIENCE : PersonalBeliefs.Sources.PERSONAL_OBSERVATION); const ambiguous = interpretation.ambiguous ?? !interpretation.reasonKnown; const personality = character.personality; let weight = ambiguous ? .12 : .2; weight *= .85 + personality.curiosity * .2 + (character.isExalted ? .15 : 0); const result = character.beliefs.upsert(type, weight, memory.id, source, interpretation.contradicts); this.world.diagnostics?.trace('beliefEvidenceAdded', { characterId: character.id, beliefType: type, memoryId: memory.id }); this.world.diagnostics?.trace(result.before ? (interpretation.contradicts ? 'beliefContradicted' : 'beliefStrengthened') : 'beliefFormed', { characterId: character.id, beliefType: type }); const faithDirection = interpretation.faithImpact ?? (interpretation.contradicts ? -.025 : .018); this.changeFaith(character, faithDirection * (.7 + personality.faithDisposition * .6)); this.notifyFormation(character, result.belief); return result.belief; }
  infer(character, memory, context) { const event = memory.eventType?.toLowerCase(); if (event === 'lightning' && context.theftKnown) return BeliefSystem.Types.THEFT; if (event === 'blessing' || event === 'shield') return context.repeatedTarget ? BeliefSystem.Types.FAVORS : context.inCrisis ? BeliefSystem.Types.PROVIDES : null; if (event === 'dry_water_source_resolved' && context.divineResolution) return BeliefSystem.Types.PROVIDES; if (event === 'lost_child_resolved' && context.divineResolution) return BeliefSystem.Types.CHILDREN; if (event === 'major_abandonment' || event === 'lost_child_failed') return BeliefSystem.Types.ABANDONED; if (event === 'castle_saved') return character.personality.faithDisposition >= .45 ? BeliefSystem.Types.CASTLE_PROTECTED : BeliefSystem.Types.UNPREDICTABLE; return null; }
  changeFaith(character, amount) { const changed = character.faith.change(amount); if (changed) this.world.diagnostics?.trace('faithChanged', { characterId: character.id, amount: changed, level: character.faith.level() }); return changed; }
  teach(speaker, listener, beliefType) { const teaching = speaker.beliefs.get(beliefType); if (!teaching || teaching.confidence < .25 || listener.lifeStage === 'child') return { outcome: 'REJECT', belief: null }; const relationship = this.world.relationships?.get?.(listener.id, speaker.id)?.trust ?? this.world.relationships?.score?.(listener.id, speaker.id) ?? .5; const contradiction = listener.beliefs.get(beliefType)?.contradictingMemories.length ?? 0; const acceptance = relationship * .36 + listener.faith.value * .3 + listener.personality.faithDisposition * .2 + (speaker.isExalted ? .12 : 0) - contradiction * .16; const outcome = acceptance >= .62 ? 'ACCEPT' : acceptance >= .4 ? 'PARTIALLY_ACCEPT' : acceptance >= .25 ? 'DOUBT' : 'REJECT'; let belief = null; if (outcome !== 'REJECT') { const source = speaker.isExalted ? PersonalBeliefs.Sources.EXALTED_TEACHING : PersonalBeliefs.Sources.TOLD_BY_OTHER; const amount = outcome === 'ACCEPT' ? .22 : outcome === 'PARTIALLY_ACCEPT' ? .14 : .08; belief = listener.beliefs.upsert(beliefType, amount, teaching.supportingMemories[0] ? `told:${speaker.id}:${teaching.supportingMemories[0]}` : `told:${speaker.id}`, source, false, speaker.id).belief; }
    this.world.diagnostics?.trace(outcome === 'REJECT' ? 'beliefRejected' : 'beliefAccepted', { speakerId: speaker.id, listenerId: listener.id, beliefType, outcome }); this.world.diagnostics?.trace('beliefTaught', { speakerId: speaker.id, listenerId: listener.id, beliefType }); return { outcome, belief };
  }
  teachingProbability(character) { return Math.min(.4, .02 + character.personality.sociability * .08 + (character.isExalted ? .18 : 0)); }
  notifyFormation(character, belief) { if (belief.confidence < .4 || this.firstBeliefNotified.has(character.id)) return; this.firstBeliefNotified.add(character.id); this.world.addEffect(character.position, 'beliefFormed', { duration: 3, message: `${character.name} crede di aver compreso qualcosa della tua volontà.` }); }
}
